<?php
/*
** Some of these variables/arrays come from peqphpeditor and allaclone
*/

return [
    'current_expansion'                 => 9,   // dragons of norrath
    'server_max_level'                  => 70,  // server max level
    'magelo_menu_name' => 'Magelo Clone',
    'magelo_base_url' => 'https://magelo.yourdomain.com/',            // https://magelo.yourdomain.com

    /**
     * NPC
     */
    'npc' => [
        'display' => [
            'ac'          => true,      // show npc ac
            'hp'          => true,      // show npc hp
            'atk'         => true,      // show npc attack value
            'dmg'         => true,      // show npc min/max dmg
            'resists'     => true,      // show npc resist values
            'abilities'   => true,      // show npc abilities (summon, enrage, etc)
            'spells'      => true,      // show npc spells
            'loot_chance' => true,      // show the drop chance % for each item
            'spawn_locs'  => true,      // enable the NPC Locations tab, atlas, and exact coordinates
            'respawn'     => true,      // hide respawn time + variance
        ],
    ],

    /**
     * Tasks
     */
    'tasks' => [
        'enable'          => true,      // disable tasks completely. Will 404 when accessed
        'display' => [
            'activities'  => true,      // show task activities
            'rewards'     => true,      // show task rewards
        ],
    ],

    'discovered_items' => [
        'enable'                    => true,   // If TRUE, only Discovered Items will be displayed
        'link_character_to_magelo'  => true,    // link character who discovered to magelo (if enabled)
        'leaderboard'               => true,    // display leaderboard for most discovered items
    ],

    'coords_as_yxz'                 => false,

    'maps' => [
        // Comma-separated map short names whose legacy geometry should be preferred.
        'legacy_zones' => array_values(array_unique(array_filter(
            array_map('trim', explode(',', (string) env(
                'EQ_MAP_LEGACY_ZONES',
                'bazaar,lavastorm,nektulos,highpasshold',
            ))),
            fn (string $zone): bool => preg_match('/^[a-z0-9]+$/', $zone) === 1,
        ))),
    ],

    // copying some of the allaclone settings for now (NOT ALL OF THESE ARE TIED BACK IN YET)
    'allow_quests_npc'              => false, // quests for npcs are available from NPC's page
    'server_max_npc_level'          => 95, // Max Level for any NPCs on the Server
    'spawngroup_around_range'       => 100, // range of surrounding spawngroups, spawngroups page
    'trackable_npcs_only'           => true, // If TRUE, will only display NPCs that are set to be trackable in search results

    /**
     * Misc
     */
    'max_recently_discovered_items'     => 25, // Max number of recently discovered items to display
    'merchants_dont_drop_stuff'         => true, // if TRUE, you won't see merchants drops, damned PEQ world builders ! :)

    'ignore_zones' => [
        'load',
        'loading',
        'load2',
        'nektropos',
        'arttest',
        'apprentice',
        'tutorial',
        'cshome',
    ],

    /*
    *****************************
    ** STOP EDITING BELOW THIS
    *****************************
    */
    'expansions' => [
        0   => 'Classic',
        1   => 'Ruins of Kunark',
        2   => 'Scars of Velious',
        3   => 'Shadows of Luclin',
        4   => 'Planes of Power',
        5   => 'Legacy of Ykesha',
        6   => 'Lost Dungeons of Norrath',
        7   => 'Gates of Discord',
        8   => 'Omens of War',
        9   => 'Dragons of Norrath',
        10  => 'Depths of Darkhollow',
        11  => 'Prophecy of Ro',
        12  => 'The Serpent\'s Spine',
        13  => 'The Buried Sea',
        14  => 'Secrets of Faydwer',
        15  => 'Seeds of Destruction',
        16  => 'Underfoot',
        17  => 'House of Thule',
        18  => 'Veil of Alaris',
        19  => 'Rain of Fear',
        20  => 'Call of the Forsaken',
        21  => 'The Darkened Sea',
        22  => 'The Broken Mirror',
        23  => 'Empires of Kunark',
        24  => 'Ring of Scale',
        25  => 'The Burning Lands',
        26  => 'Torment of Velious',
        27  => 'Claws of Veeshan',
        28  => 'Terror of Luclin',
        29  => 'Night of Shadows',
        30  => 'Laurion\'s Song',
        31 => 'The Outer Brood',
        32 => 'Shattering of Ro',
    ],

    // https://github.com/EQEmu/Server/blob/master/common/races.h
    'races' => [
        1   => 'Human',
        2   => 'Barbarian',
        3   => 'Erudite',
        4   => 'Wood Elf',
        5   => 'High Elf',
        6   => 'Dark Elf',
        7   => 'Half Elf',
        8   => 'Dwarf',
        9   => 'Troll',
        10  => 'Ogre',
        11  => 'Halfling',
        12  => 'Gnome',
        128 => 'Iksar',
        130 => 'Vah Shir',
        330 => 'Froglok',
        522 => 'Drakkin',
    ],

    // https://github.com/EQEmu/eqemu-docs-v2/blob/main/docs/server/player/class-list.md
    'classes' => [
        1   => 'Warrior',
        2   => 'Cleric',
        3   => 'Paladin',
        4   => 'Ranger',
        5   => 'Shadow Knight',
        6   => 'Druid',
        7   => 'Monk',
        8   => 'Bard',
        9   => 'Rogue',
        10  => 'Shaman',
        11  => 'Necromancer',
        12  => 'Wizard',
        13  => 'Magician',
        14  => 'Enchanter',
        15  => 'Beastlord',
        16  => 'Berserker',
    ],

    'classes_abbr' => [
        1   => 'WAR',
        2   => 'CLR',
        3   => 'PAL',
        4   => 'RNG',
        5   => 'SHD',
        6   => 'DRU',
        7   => 'MNK',
        8   => 'BRD',
        9   => 'ROG',
        10  => 'SHM',
        11  => 'NEC',
        12  => 'WIZ',
        13  => 'MAG',
        14  => 'ENC',
        15  => 'BST',
        16  => 'BER',
    ],

    'pet_classes' => [
        15  => 'Beastlord',
        2   => 'Cleric',
        6   => 'Druid',
        14  => 'Enchanter',
        13  => 'Magician',
        11  => 'Necromancer',
        5   => 'Shadow Knight',
        10  => 'Shaman',
        12  => 'Wizard',
    ],

    'bagtypes' => [
        0   => 'SMALLBAG',
        1   => 'LARGEBAG',
        2   => 'QUIVER',
        3   => 'BELTPOUCH',
        4   => 'WRISTPOUCH',
        5   => 'BACKPACK',
        6   => 'SMALLCHEST',
        7   => 'LARGECHEST',
        8   => 'BANDOLIER',
        9   => 'MEDICINE',
        10  => 'TINKERING',
        11  => 'LEXICON',
        12  => 'POISONMAKING',
        13  => 'QUEST',
        14  => 'MIXINGBOWL',
        15  => 'BAKING',
        16  => 'TAILORING',
        17  => 'BLACKSMITHING',
        18  => 'FLETCHING',
        19  => 'BREWING',
        20  => 'JEWELRYMAKING',
        21  => 'POTTERY',
        22  => 'KILN',
        23  => 'KEYMAKER',
        24  => 'RESEARCHWIZ',
        25  => 'RESEARCHMAG',
        26  => 'RESEARCHNEC',
        27  => 'RESEARCHENC',
        28  => 'UNKNOWN28',
        29  => 'RESEARCHPRACTICE',
        30  => 'ALCHEMY',
        31  => 'HIGHELFFORGE',
        32  => 'DARKELFFORGE',
        33  => 'OGREFORGE',
        34  => 'DWARFFORGE',
        35  => 'GNOMEFORGE',
        36  => 'BARBARIANFORGE',
        37  => 'IKSARFORGE',
        38  => 'HUMANFORGEONE',
        39  => 'HUMANFORGETWO',
        40  => 'HALFLINGTAILORINGONE',
        41  => 'HALFLINGTAILORINGTWO',
        42  => 'ERUDITETAILORING',
        43  => 'WOODELFTAILORING',
        44  => 'WOODELFFLETCHING',
        45  => 'IKSARPOTTERY',
        46  => 'FISHING',
        47  => 'TROLLFORGE',
        48  => 'WOODELFFORGE',
        49  => 'HALFLINGFORGE',
        50  => 'ERUDITEFORGE',
        51  => 'MERCHANT',
        52  => 'FROGLOKFORGE',
        53  => 'AUGMENTER',
        54  => 'CHURN',
        55  => 'TRANSFORMATIONMOLD',
        56  => 'DETRANSFORMATIONMOLD',
        57  => 'UNATTUNER',
        58  => 'TRADESKILLBAG',
        59  => 'COLLECTIBLEBAG',
        60  => 'NODEPOSIT',
        255 => 'TAANAN?',
    ],

    /*
    ** ALLA DB BITMASK STUFF
    */
    'classes_short' => [
        65535   => 'ALL',
        32768   => 'BER',
        16384   => 'BST',
        8192    => 'ENC',
        4096    => 'MAG',
        2048    => 'WIZ',
        1024    => 'NEC',
        512     => 'SHM',
        256     => 'ROG',
        128     => 'BRD',
        64      => 'MNK',
        32      => 'DRU',
        16      => 'SHD',
        8       => 'RNG',
        4       => 'PAL',
        2       => 'CLR',
        1       => 'WAR',
    ],

    'races_short' => [
        65535   => 'ALL',
        32768   => 'DRK',
        16384   => 'FRG',
        8192    => 'VAH',
        4096    => 'IKS',
        2048    => 'GNM',
        1024    => 'HFL',
        512     => 'OGR',
        256     => 'TRL',
        128     => 'DWF',
        64      => 'HLF',
        32      => 'DKE',
        16      => 'HEF',
        8       => 'WLF',
        4       => 'ERU',
        2       => 'BAR',
        1       => 'HUM',
    ],

    'deities_short' => [
        65536   => 'Veeshan',
        32768   => 'Tunare',
        16384   => 'The Tribunal',
        8192    => 'Solusek Ro',
        4096    => 'Rodcet Nife',
        2048    => 'Rallos Zek',
        1024    => 'Quellious',
        512     => 'Prexus',
        256     => 'Mithaniel Marr',
        128     => 'Karana',
        64      => 'Innoruuk',
        32      => 'Bristlebane',
        16      => 'Erollisi Marr',
        8       => 'Cazic Thule',
        4       => 'Brell Serilis',
        2       => 'Bertoxxulous',
    ],

    'classes_bit' => [
        1     => 'Warrior',
        2     => 'Cleric',
        4     => 'Paladin',
        8     => 'Ranger',
        16    => 'Shadowknight',
        32    => 'Druid',
        64    => 'Monk',
        128   => 'Bard',
        256   => 'Rogue',
        512   => 'Shaman',
        1024  => 'Necromancer',
        2048  => 'Wizard',
        4096  => 'Magician',
        8192  => 'Enchanter',
        16384 => 'Beastlord',
        32768 => 'Berserker',
    ],

    'classes_bit_abbr' => [
        1     => 'WAR',
        2     => 'CLR',
        4     => 'PAL',
        8     => 'RNG',
        16    => 'SHD',
        32    => 'DRU',
        64    => 'MNK',
        128   => 'BRD',
        256   => 'ROG',
        512   => 'SHM',
        1024  => 'NEC',
        2048  => 'WIZ',
        4096  => 'MAG',
        8192  => 'ENC',
        16384 => 'BST',
        32768 => 'BER',
    ],

    'races_bit' => [
        1     => 'Human',
        2     => 'Barbarian',
        4     => 'Erudite',
        8     => 'Wood Elf',
        16    => 'High Elf',
        32    => 'Dark Elf',
        64    => 'Half Elf',
        128   => 'Dwarf',
        256   => 'Troll',
        512   => 'Ogre',
        1024  => 'Halfling',
        2048  => 'Gnome',
        4096  => 'Iksar',
        8192  => 'Vah Shir',
        16384 => 'Froglok',
        32768 => 'Drakkin',
    ],

    'deities_bit' => [
        1     => 'Agnostic',
        2     => 'Bertoxxulous',
        4     => 'Brell Serilis',
        8     => 'Cazic Thule',
        16    => 'Erollisi Marr',
        32    => 'Bristlebane',
        64    => 'Innoruuk',
        128   => 'Karana',
        256   => 'Mithaniel Marr',
        512   => 'Prexus',
        1024  => 'Quellious',
        2048  => 'Rallos Zek',
        4096  => 'Rodcet Nife',
        8192  => 'Solusek Ro',
        16384 => 'The Tribunal',
        32768 => 'Tunare',
        65536 => 'Veeshan',
    ],

    'slots' => [
        2097152 => 'Power Source',
        4194304 => 'Ammo',
        1048576 => 'Waist',
        524288  => 'Feet',
        262144  => 'Legs',
        131072  => 'Chest',
        98304   => 'Fingers',
        65536   => 'Finger 2',
        32768   => 'Finger 1',
        16384   => 'Secondary',
        8192    => 'Primary',
        4096    => 'Hands',
        2048    => 'Range',
        1536    => 'Wrists',
        1024    => 'Wrist 2',
        512     => 'Wrist 1',
        256     => 'Back',
        128     => 'Arms',
        64      => 'Shoulders',
        32      => 'Neck',
        18      => 'Ears',
        16      => 'Ear 2',
        8       => 'Face',
        4       => 'Head',
        2       => 'Ear 1',
        1       => 'Charm',
    ],

    'item_types' => [
        0   => '1H Slashing',
        1   => '2H Slashing',
        2   => 'Piercing',
        3   => '1H Blunt',
        4   => '2H Blunt',
        5   => 'Archery',
        6   => 'Crossbow',
        7   => 'Throwing v1',
        8   => 'Shield',
        9   => 'Spell',
        10  => 'Armor',
        11  => 'Misc',
        12  => 'Lockpicks',
        13  => 'Fist',
        14  => 'Food',
        15  => 'Drink',
        16  => 'Light',
        17  => 'Combinable',
        18  => 'Bandages',
        19  => 'Throwing v2',
        20  => 'Scroll',
        21  => 'Potion',
        22  => 'Fletched Arrow',
        23  => 'Wind Instrument',
        24  => 'Stringed Instrument',
        25  => 'Brass Instrument',
        26  => 'Percussion Instrument',
        27  => 'Arrow',
        28  => 'Bolt',
        29  => 'Jewelry',
        30  => 'Skull',
        31  => 'Book',
        32  => 'Note',
        33  => 'Key v1',
        34  => 'Coin',
        35  => '2H Piercing',
        36  => 'Fishing Pole',
        37  => 'Fishing Bait',
        38  => 'Alcohol',
        39  => 'Key v2',
        40  => 'Compass',
        41  => 'Metal Key',
        42  => 'Poison',
        43  => 'Magic Arrow',
        44  => 'Magic Bolt',
        45  => 'Hand to Hand',
        46  => 'Item Has Effect',
        47  => 'Haste Item',
        48  => 'Item Has FT',
        49  => 'Item Has Focus',
        50  => 'Singing Instrument',
        51  => 'All Instruments',
        52  => 'Charm',
        53  => 'Armor Dye',
        54  => 'Augment',
        55  => 'Augment Solvent',
        56  => 'Augment Distiller',
        57  => 'Alternate Ability',
        58  => 'Guild Banner Kit',
        59  => 'Guild Banner Modify Token',
        60  => 'Cultural Armor Recipe Book',
        61  => 'Cultural Weapon Recipe Book',
        62  => 'Book with Spell Effect',
        63  => 'Alternate Currency',
        64  => 'Perfected Augment Distiller',
        65  => 'Placeable',
        66  => 'Collectible',
        67  => 'Container',
        68  => 'Mount',
        69  => 'Illusion',
        70  => 'Familiar',
        71  => 'Unknown71',
        72  => 'Unknown72',
        255 => 'None'
    ],

    'db_elements' => [
        0 => 'Unresistable',
        1 => 'Magic',
        2 => 'Fire',
        3 => 'Cold',
        4 => 'Poison',
        5 => 'Disease',
        6 => 'Chromatic',
        7 => 'Prismatic',
        8 => 'Physical',
        9 => 'Corruption',
    ],

    // thanks to peqphpeditor
    'db_races' => [
        0    => 'Doug',
        1    => 'Human',
        2    => 'Barbarian',
        3    => 'Erudite',
        4    => 'Wood Elf',
        5    => 'High Elf',
        6    => 'Dark Elf',
        7    => 'Half Elf',
        8    => 'Dwarf',
        9    => 'Troll',
        10   => 'Ogre',
        11   => 'Halfling',
        12   => 'Gnome',
        13   => 'Aviak',
        14   => 'Werewolf',
        15   => 'Brownie',
        16   => 'Centaur',
        17   => 'Golem',
        18   => 'Giant/Cyclops',
        19   => 'Trakanon',
        20   => '4-arm/Venril Sathir',
        21   => 'Evil Eye',
        22   => 'Beetle',
        23   => 'Kerran',
        24   => 'Fish',
        25   => 'Fairy',
        26   => 'Froglok',
        27   => 'Froglok Ghoul',
        28   => 'Fungusman',
        29   => 'Gargoyle',
        30   => 'Gasbag',
        31   => 'Gelatinous Cube',
        32   => 'Ghost',
        33   => 'Ghoul',
        34   => 'Giant Bat',
        35   => 'Giant Eel',
        36   => 'Giant Rat',
        37   => 'Giant Snake',
        38   => 'Giant Spider',
        39   => 'Gnoll',
        40   => 'Goblin',
        41   => 'Gorilla',
        42   => 'Wolf',
        43   => 'Bear',
        44   => 'Freeport Guard',
        45   => 'Demi Lich',
        46   => 'Imp',
        47   => 'Griffin',
        48   => 'Kobold',
        49   => 'Lava Dragon',
        50   => 'Lion',
        51   => 'Lizard Man',
        52   => 'Mimic',
        53   => 'Minotaur',
        54   => 'Orc',
        55   => 'Human Beggar',
        56   => 'Pixie',
        57   => 'Dracnid',
        58   => 'Solusek Ro',
        59   => 'Bloodgill',
        60   => 'Skeleton',
        61   => 'Shark',
        62   => 'Tunare',
        63   => 'Tiger',
        64   => 'Treant',
        65   => 'Vampire',
        66   => 'Statue of Rallos Zek',
        67   => 'Highpass Citizen',
        68   => 'Tentacle',
        69   => 'Wisp',
        70   => 'Zombie',
        71   => 'Qeynos Citizen',
        72   => 'Ship',
        73   => 'Launch',
        74   => 'Piranha',
        75   => 'Elemental',
        76   => 'Puma',
        77   => 'Neriak Citizen',
        78   => 'Erudite Citizen',
        79   => 'Bixie',
        80   => 'Reanimated Hand',
        81   => 'Rivervale Citizen',
        82   => 'Scarecrow',
        83   => 'Skunk',
        84   => 'Snake Elemental',
        85   => 'Spectre',
        86   => 'Sphinx',
        87   => 'Armadillo',
        88   => 'Clockwork Gnome',
        89   => 'Drake',
        90   => 'Halas Citizen',
        91   => 'Alligator',
        92   => 'Grobb Citizen',
        93   => 'Oggok Citizen',
        94   => 'Kaladim Citizen',
        95   => 'Cazic Thule',
        96   => 'Cockatrice',
        97   => 'Daisy Man',
        98   => 'Elf Vampire',
        99   => 'Denizen',
        100  => 'Dervish',
        101  => 'Efreeti',
        102  => 'Froglok Tadpole',
        103  => 'Phinigel Autropos',
        104  => 'Leech',
        105  => 'Swordfish',
        106  => 'Felguard',
        107  => 'Mammoth',
        108  => 'Eye of Zomm',
        109  => 'Wasp',
        110  => 'Mermaid',
        111  => 'Harpie',
        112  => 'Fayguard',
        113  => 'Drixie',
        114  => 'Ghost Ship',
        115  => 'Clam',
        116  => 'Sea Horse',
        117  => 'Dwarf Ghost',
        118  => 'Erudite Ghost',
        119  => 'Sabertooth',
        120  => 'Wolf Elemental',
        121  => 'Gorgon',
        122  => 'Dragon Skeleton',
        123  => 'Innoruuk',
        124  => 'Unicorn',
        125  => 'Pegasus',
        126  => 'Djinn',
        127  => 'Invisible Man',
        128  => 'Iksar',
        129  => 'Scorpion',
        130  => 'Vah Shir',
        131  => 'Sarnak',
        132  => 'Draglock',
        133  => 'Lycanthrope',
        134  => 'Mosquito',
        135  => 'Rhino',
        136  => 'Xalgoz',
        137  => 'Kunark Goblin',
        138  => 'Yeti',
        139  => 'Iksar Citizen',
        140  => 'Forest Giant',
        141  => 'Boat',
        142  => 'Minor Illusion',
        143  => 'Tree Illusion',
        144  => 'Burynai',
        145  => 'Goo',
        146  => 'Spectral Sarnak',
        147  => 'Spectral Iksar',
        148  => 'Kunark Fish',
        149  => 'Iksar Scorpion',
        150  => 'Erollisi',
        151  => 'Tribunal',
        152  => 'Bertoxxulous',
        153  => 'Bristlebane',
        154  => 'Fay Drake',
        155  => 'Sarnak Skeleton',
        156  => 'Ratman',
        157  => 'Wyvern',
        158  => 'Wurm',
        159  => 'Devourer',
        160  => 'Iksar Golem',
        161  => 'Iksar Skeleton',
        162  => 'Man Eating Plant',
        163  => 'Raptor',
        164  => 'Sarnak Golem',
        165  => 'Water Dragon',
        166  => 'Iksar Hand',
        167  => 'Succulent',
        168  => 'Holgresh',
        169  => 'Brontotherium',
        170  => 'Snow Dervish',
        171  => 'Dire Wolf',
        172  => 'Manticore',
        173  => 'Totem',
        174  => 'Cold Spectre',
        175  => 'Enchanted Armor',
        176  => 'Snow Bunny',
        177  => 'Walrus',
        178  => 'Rock-gem Man',
        179  => 'Unknown179',
        180  => 'Unknown180',
        181  => 'Yak Man',
        182  => 'Faun',
        183  => 'Coldain',
        184  => 'Velious Dragon',
        185  => 'Hag',
        186  => 'Hippogriff',
        187  => 'Siren',
        188  => 'Frost Giant',
        189  => 'Storm Giant',
        190  => 'Otterman',
        191  => 'Walrus Man',
        192  => 'Clockwork Dragon',
        193  => 'Abhorrent',
        194  => 'Sea Turtle',
        195  => 'Black and White Dragon',
        196  => 'Ghost Dragon',
        197  => 'Ronnie Test',
        198  => 'Prismatic Dragon',
        199  => 'Shiknar',
        200  => 'Rockhopper',
        201  => 'Underbulk',
        202  => 'Grimling',
        203  => 'Vacuum Worm',
        204  => 'Evan Test',
        205  => 'Kahli Shah',
        206  => 'Owlbear',
        207  => 'Rhino Beetle',
        208  => 'Vampyre',
        209  => 'Earth Elemental',
        210  => 'Air Elemental',
        211  => 'Water Elemental',
        212  => 'Fire Elemental',
        213  => 'Wetfang Minnow',
        214  => 'Thought Horror',
        215  => 'Tegi',
        216  => 'Horse',
        217  => 'Shissar',
        218  => 'Fungal Fiend',
        219  => 'Vampire Volatalis',
        220  => 'StoneGrabber',
        221  => 'Scarlet Cheetah',
        222  => 'Zelniak',
        223  => 'Lightcrawler',
        224  => 'Shade',
        225  => 'Sunflower',
        226  => 'Khati Sha',
        227  => 'Shrieker',
        228  => 'Galorian',
        229  => 'Netherbian',
        230  => 'Akhevan',
        231  => 'Spire Spirit',
        232  => 'Sonic Wolf',
        233  => 'Ground Shaker',
        234  => 'Vah Shir Skeleton',
        235  => 'Mutant Humanoid',
        236  => 'Lord Inquisitor Seru',
        237  => 'Recuso',
        238  => 'Vah Shir King',
        239  => 'Vah Shir Guard',
        240  => 'Teleport Man',
        241  => 'Lujein',
        242  => 'Naiad',
        243  => 'Nymph',
        244  => 'Ent',
        245  => 'Wrinnfly',
        246  => 'Coirnav',
        247  => 'Solusek Ro',
        248  => 'Clockwork Golem',
        249  => 'Clockwork Brain',
        250  => 'Spectral Banshee',
        251  => 'Guard of Justice',
        252  => 'PoM Castle',
        253  => 'Disease Boss',
        254  => 'Solusek Ro Guard',
        255  => 'Bertoxxulous (New)',
        256  => 'Tribunal (New)',
        257  => 'Terris Thule',
        258  => 'Vegerog',
        259  => 'Crocodile',
        260  => 'Bat',
        261  => 'Slarghilug',
        262  => 'Tranquilion',
        263  => 'Tin Soldier',
        264  => 'Nightmare Wraith',
        265  => 'Malarian',
        266  => 'Knight of Pestilence',
        267  => 'Lepertoloth',
        268  => 'Bubonian Boss',
        269  => 'Bubonian Underling',
        270  => 'Pusling',
        271  => 'Water Mephit',
        272  => 'Stormrider',
        273  => 'Junk Beast',
        274  => 'Broken Clockwork',
        275  => 'Giant Clockwork',
        276  => 'Clockwork Beetle',
        277  => 'Nightmare Goblin',
        278  => 'Karana',
        279  => 'Blood Raven',
        280  => 'Nightmare Gargoyle',
        281  => 'Mouth of Insanity',
        282  => 'Skeletal Horse',
        283  => 'Saryrn',
        284  => 'Fennin Ro',
        285  => 'Tormentor',
        286  => 'Necromancer Priest',
        287  => 'Nightmare',
        288  => 'New Rallos Zek',
        289  => 'Vallon Zek',
        290  => 'Tallon Zek',
        291  => 'Air Mephit',
        292  => 'Earth Mephit',
        293  => 'Fire Mephit',
        294  => 'Nightmare Mephit',
        295  => 'Zebuxoruk',
        296  => 'Mithaniel Marr',
        297  => 'Knightmare Rider',
        298  => 'Rathe Councilman',
        299  => 'Xegony',
        300  => 'Demon/Fiend',
        301  => 'Test Object',
        302  => 'Lobster Monster',
        303  => 'Phoenix',
        304  => 'Quarm',
        305  => 'New Bear',
        306  => 'Earth Golem',
        307  => 'Iron Golem',
        308  => 'Storm Golem',
        309  => 'Air Golem',
        310  => 'Wood Golem',
        311  => 'Fire Golem',
        312  => 'Water Golem',
        313  => 'Veiled Gargoyle',
        314  => 'Lynx',
        315  => 'Squid',
        316  => 'Frog',
        317  => 'Flying Serpent',
        318  => 'Tactics Soldier',
        319  => 'Armored Boar',
        320  => 'Djinni',
        321  => 'Boar',
        322  => 'Knight of Marr',
        323  => 'Armor of Marr',
        324  => 'Nightmare Knight',
        325  => 'Rallos Ogre',
        326  => 'Arachnid',
        327  => 'Crystal Arachnid',
        328  => 'Tower Model',
        329  => 'Portal',
        330  => 'Froglok',
        331  => 'Troll Crew Member',
        332  => 'Pirate Deckhand',
        333  => 'Broken Skull Pirate',
        334  => 'Pirate Ghost',
        335  => 'One-armed Pirate',
        336  => 'Spiritmaster Nadox',
        337  => 'Broken Skull Taskmaster',
        338  => 'Gnome Pirate',
        339  => 'Dark Elf Pirate',
        340  => 'Ogre Pirate',
        341  => 'Human Pirate',
        342  => 'Erudite Pirate',
        343  => 'Frog',
        344  => 'Undead Pirate',
        345  => 'Luggald Worker',
        346  => 'Luggald Soldier',
        347  => 'Luggald Disciple',
        348  => 'Drogmor',
        349  => 'Froglok Skeleton',
        350  => 'Undead Froglok',
        351  => 'Knight of Hate',
        352  => 'Warlock of Hate',
        353  => 'Highborn',
        354  => 'Highborn Diviner',
        355  => 'Highborn Crusader',
        356  => 'Chokidai',
        357  => 'Undead Chokidai',
        358  => 'Undead Veksar',
        359  => 'Undead Vampire',
        360  => 'Vampire',
        361  => 'Rujarkian Orc',
        362  => 'Bone Golem',
        363  => 'Synarcana',
        364  => 'Sand Elf',
        365  => 'Master Vampire',
        366  => 'Master Orc',
        367  => 'New Skeleton',
        368  => 'Crypt Creeper',
        369  => 'New Goblin',
        370  => 'Burrower Bug',
        371  => 'Froglok Ghost',
        372  => 'Vortex',
        373  => 'Shadow',
        374  => 'Golem Beast',
        375  => 'Watchful Eye',
        376  => 'Box',
        377  => 'Barrel',
        378  => 'Chest',
        379  => 'Vase',
        380  => 'Frozen Table',
        381  => 'Weapon Rack',
        382  => 'Coffin',
        383  => 'Skull and Bones',
        384  => 'Jester',
        385  => 'Taelosian Native',
        386  => 'Taelosian Evoker',
        387  => 'Taelosian Golem',
        388  => 'Taelosian Wolf',
        389  => 'Taelosian Amphibian Creature',
        390  => 'Taelosian Mountain Beast',
        391  => 'Taelosian Stonemite',
        392  => 'Ukun War Hound',
        393  => 'Ixt Centaur',
        394  => 'Ikaav Snakewoman',
        395  => 'Aneuk',
        396  => 'Kyv Hunter',
        397  => 'Noc Sprayblood',
        398  => 'Ratuk Brute',
        399  => 'Ixt',
        400  => 'Huvul',
        401  => 'Mastruq Warfiend',
        402  => 'Mastruq',
        403  => 'Taelosian',
        404  => 'Ship',
        405  => 'New Golem',
        406  => 'Overlord Mata Muram',
        407  => 'Lighting warrior',
        408  => 'Succubus',
        409  => 'Bazu',
        410  => 'Feran',
        411  => 'Pyrilen',
        412  => 'Chimera',
        413  => 'Dragorn',
        414  => 'Murkglider',
        415  => 'Rat',
        416  => 'Bat',
        417  => 'Gelidran',
        418  => 'Discordling',
        419  => 'Girplan',
        420  => 'Minotaur',
        421  => 'Dragorn Box',
        422  => 'Runed Orb',
        423  => 'Dragon Bones',
        424  => 'Muramite Armor Pile',
        425  => 'Crystal Shard',
        426  => 'Portal',
        427  => 'Coin Purse',
        428  => 'Rock Pile',
        429  => 'Murkglider Egg Sack',
        430  => 'Drake',
        431  => 'Dervish',
        432  => 'Drake',
        433  => 'Goblin',
        434  => 'Kirin',
        435  => 'Dragon',
        436  => 'Basilisk',
        437  => 'Dragon',
        438  => 'Dragon',
        439  => 'Puma',
        440  => 'Spider',
        441  => 'Spider Queen',
        442  => 'Animated Statue',
        443  => 'Unknown443',
        444  => 'Unknown444',
        445  => 'Dragon Egg',
        446  => 'Dragon Statue',
        447  => 'Lava Rock',
        448  => 'Animated Statue',
        449  => 'Spider Egg Sack',
        450  => 'Lava Spider',
        451  => 'Lava Spider Queen',
        452  => 'Dragon',
        453  => 'Giant',
        454  => 'Werewolf',
        455  => 'Kobold',
        456  => 'Sporali',
        457  => 'Gnomework',
        458  => 'Orc',
        459  => 'Corathus',
        460  => 'Coral',
        461  => 'Drachnid',
        462  => 'Drachnid Cocoon',
        463  => 'Fungus Patch',
        464  => 'Gargoyle',
        465  => 'Witheran',
        466  => 'Dark Lord',
        467  => 'Shiliskin',
        468  => 'Snake',
        469  => 'Evil Eye',
        470  => 'Minotaur',
        471  => 'Zombie',
        472  => 'Clockwork Boar',
        473  => 'Fairy',
        474  => 'Witheran',
        475  => 'Air Elemental',
        476  => 'Earth Elemental',
        477  => 'Fire Elemental',
        478  => 'Water Elemental',
        479  => 'Alligator',
        480  => 'Bear',
        481  => 'Scaled Wolf',
        482  => 'Wolf',
        483  => 'Spirit Wolf',
        484  => 'Skeleton',
        485  => 'Spectre',
        486  => 'Bolvirk',
        487  => 'Banshee',
        488  => 'Banshee',
        489  => 'Elddar',
        490  => 'Forest Giant',
        491  => 'Bone Golem',
        492  => 'Horse',
        493  => 'Pegasus',
        494  => 'Shambling Mound',
        495  => 'Scrykin',
        496  => 'Treant',
        497  => 'Vampire',
        498  => 'Ayonae Ro',
        499  => 'Sullon Zek',
        500  => 'Banner',
        501  => 'Flag',
        502  => 'Rowboat',
        503  => 'Bear Trap',
        504  => 'Clockwork Bomb',
        505  => 'Dynamite Keg',
        506  => 'Pressure Plate',
        507  => 'Puffer Spore',
        508  => 'Stone Ring',
        509  => 'Root Tentacle',
        510  => 'Runic Symbol',
        511  => 'Saltpetter Bomb',
        512  => 'Floating Skull',
        513  => 'Spike Trap',
        514  => 'Totem',
        515  => 'Web',
        516  => 'Wicker Basket',
        517  => 'Nightmare/Unicorn',
        518  => 'Horse',
        519  => 'Nightmare/Unicorn',
        520  => 'Bixie',
        521  => 'Centaur',
        522  => 'Drakkin',
        523  => 'Giant',
        524  => 'Gnoll',
        525  => 'Griffin',
        526  => 'Giant Shade',
        527  => 'Harpy',
        528  => 'Mammoth',
        529  => 'Satyr',
        530  => 'Dragon',
        531  => 'Dragon',
        532  => 'DynLeth',
        533  => 'Boat',
        534  => 'Weapon Rack',
        535  => 'Armor Rack',
        536  => 'Honey Pot',
        537  => 'Jum Jum Bucket',
        538  => 'Plant',
        539  => 'Plant',
        540  => 'Plant',
        541  => 'Toolbox',
        542  => 'Wine Cask',
        543  => 'Stone Jug',
        544  => 'Elven Boat',
        545  => 'Gnomish Boat',
        546  => 'Barrel Barge Ship',
        547  => 'Goo',
        548  => 'Goo',
        549  => 'Goo',
        550  => 'Merchant Ship',
        551  => 'Pirate Ship',
        552  => 'Ghost Ship',
        553  => 'Banner',
        554  => 'Banner',
        555  => 'Banner',
        556  => 'Banner',
        557  => 'Banner',
        558  => 'Aviak',
        559  => 'Beetle',
        560  => 'Gorilla',
        561  => 'Kedge',
        562  => 'Kerran',
        563  => 'Shissar',
        564  => 'Siren',
        565  => 'Sphinx',
        566  => 'Human',
        567  => 'Campfire',
        568  => 'Brownie',
        569  => 'Dragon',
        570  => 'Exoskeleton',
        571  => 'Ghoul',
        572  => 'Clockwork Guardian',
        573  => 'Mantrap',
        574  => 'Minotaur',
        575  => 'Scarecrow',
        576  => 'Shade',
        577  => 'Rotocopter',
        578  => 'Tentacle Terror',
        579  => 'Wereorc',
        580  => 'Worg',
        581  => 'Wyvern',
        582  => 'Chimera',
        583  => 'Kirin',
        584  => 'Puma',
        585  => 'Boulder',
        586  => 'Banner',
        587  => 'Elven Ghost',
        588  => 'Human Ghost',
        589  => 'Chest',
        590  => 'Chest',
        591  => 'Crystal',
        592  => 'Coffin',
        593  => 'Guardian CPU',
        594  => 'Worg',
        595  => 'Mansion',
        596  => 'Floating Island',
        597  => 'Cragslither',
        598  => 'Wrulon',
        599  => 'Spell Particle 1',
        600  => 'Invisible Man of Zomm',
        601  => 'Robocopter of Zomm',
        602  => 'Burynai',
        603  => 'Frog',
        604  => 'Dracolich',
        605  => 'Iksar Ghost',
        606  => 'Iksar Skeleton',
        607  => 'Mephit',
        608  => 'Muddite',
        609  => 'Raptor',
        610  => 'Sarnak',
        611  => 'Scorpion',
        612  => 'Tsetsian',
        613  => 'Wurm',
        614  => 'Balrog',
        615  => 'Hydra Crystal',
        616  => 'Crystal Sphere',
        617  => 'Gnoll',
        618  => 'Sokokar',
        619  => 'Stone Pylon',
        620  => 'Demon Vulture',
        621  => 'Wagon',
        622  => 'God of Discord',
        623  => 'Wrulon Mount',
        624  => 'Ogre NPC - Male',
        625  => 'Sokokar Mount',
        626  => 'Giant (Rallosian mats)',
        627  => 'Sokokar (w saddle)',
        628  => '10th Anniversary Banner',
        629  => '10th Anniversary Cake',
        630  => 'Wine Cask',
        631  => 'Hydra Mount',
        632  => 'Hydra NPC',
        633  => 'Wedding Flowers',
        634  => 'Wedding Arbor',
        635  => 'Wedding Altar',
        636  => 'Powder Keg',
        637  => 'Apexus',
        638  => 'Bellikos',
        639  => 'Brells First Creation',
        640  => 'Brell',
        641  => 'Crystalskin Ambuloid',
        642  => 'Cliknar Queen',
        643  => 'Cliknar Soldier',
        644  => 'Cliknar Worker',
        645  => 'Coldain',
        646  => 'Coldain',
        647  => 'Crystalskin Sessiloid',
        648  => 'Genari',
        649  => 'Gigyn',
        650  => 'Greken - Young Adult',
        651  => 'Greken - Young',
        652  => 'Cliknar Mount',
        653  => 'Telmira',
        654  => 'Spider Mount',
        655  => 'Bear Mount',
        656  => 'Rat Mount',
        657  => 'Sessiloid Mount',
        658  => 'Morell Thule',
        659  => 'Marionette',
        660  => 'Book Dervish',
        661  => 'Topiary Lion',
        662  => 'Rotdog',
        663  => 'Amygdalan',
        664  => 'Sandman',
        665  => 'Grandfather Clock',
        666  => 'Gingerbread Man',
        667  => 'Beefeater',
        668  => 'Rabbit',
        669  => 'Blind Dreamer',
        670  => 'Cazic Thule',
        671  => 'Topiary Lion Mount',
        672  => 'Rot Dog Mount',
        673  => 'Goral Mount',
        674  => 'Selyran Mount',
        675  => 'Sclera Mount',
        676  => 'Braxy Mount',
        677  => 'Kangon Mount',
        678  => 'Erudite',
        679  => 'Wurm Mount',
        680  => 'Raptor Mount',
        681  => 'Invisible Man',
        682  => 'Whirligig',
        683  => 'Gnomish Balloon',
        684  => 'Gnomish Rocket Pack',
        685  => 'Gnomish Hovering Transport',
        686  => 'Selyrah',
        687  => 'Goral',
        688  => 'Braxi',
        689  => 'Kangon',
        690  => 'Invisible Man',
        691  => 'Floating Tower',
        692  => 'Explosive Cart',
        693  => 'Blimp Ship',
        694  => 'Tumbleweed',
        695  => 'Alaran',
        696  => 'Swinetor',
        697  => 'Triumvirate',
        698  => 'Hadal',
        699  => 'Hovering Platform',
        700  => 'Parasitic Scavenger',
        701  => 'Grendlaen',
        702  => 'Ship in a Bottle',
        703  => 'Alaran Sentry Stone',
        704  => 'Dervish',
        705  => 'Regeneration Pool',
        706  => 'Teleportation Stand',
        707  => 'Relic Case',
        708  => 'Alaran Ghost',
        709  => 'Skystrider',
        710  => 'Water Spout',
        711  => 'Aviak Pull Along',
        712  => 'Gelatinous Cube',
        713  => 'Cat',
        714  => 'Elk Head',
        715  => 'Holgresh',
        716  => 'Beetle',
        717  => 'Vine Maw',
        718  => 'Ratman',
        719  => 'Fallen Knight',
        720  => 'Flying Carpet',
        721  => 'Carrier Hand',
        722  => 'Fallen Knight',
        723  => 'Servant of Shadow',
        724  => 'Luclin',
        2250 => 'Interactive Object',
    ],

    // thanks to peqphpeditor
    'db_bodytypes' => [
        0   => 'Object', // Catapults, Tents, Practice Dummies, etc.
        1   => 'Humanoid',
        2   => 'Lycanthrope',
        3   => 'Undead',
        4   => 'Giant',
        5   => 'Construct', // Includes confused mutations in LDoN chests
        6   => 'Extraplanar',
        7   => 'Magical',
        8   => 'Undead Pet',
        9   => 'Bane Giant',
        10  => 'Dain',
        11  => 'Untargetable',
        12  => 'Vampyre',
        13  => 'Atenha Ra',
        14  => 'Greater Akheva',
        15  => 'Khati Sha',
        16  => 'Seru',
        17  => 'Greig',
        18  => 'Draz Nurakk',
        19  => 'Zek',
        20  => 'Luggald',
        21  => 'Animal',
        22  => 'Insect',
        23  => 'Monster',
        24  => 'Elemental',
        25  => 'Plant',
        26  => 'Dragon',
        27  => 'Elemental',
        28  => 'Summoned Creature',
        29  => 'Puff Dragon',
        30  => 'Bane Dragon',
        31  => 'Familiar',
        32  => 'Proc Pet', // NoCorpseNpc
        33  => 'Cursed', // 5
        34  => 'Muramite',
        35  => 'Unknown35',
        36  => 'Unknown36',
        37  => 'Unknown37',
        38  => 'Unknown38',
        39  => 'Unknown39',
        40  => 'Unknown40',
        41  => 'Unknown41',
        42  => 'Unknown42',
        43  => 'Unknown43',
        44  => 'Unknown44',
        45  => 'Unknown45',
        46  => 'Unknown46',
        47  => 'Unknown47',
        48  => 'Unknown48',
        49  => 'Unknown49',
        50  => 'Unknown50',
        51  => 'Unknown51',
        52  => 'Unknown52',
        53  => 'Unknown53',
        54  => 'Unknown54',
        55  => 'Unknown55',
        56  => 'Unknown56',
        57  => 'Unknown57',
        58  => 'Unknown58',
        59  => 'Unknown59',
        60  => 'NoTarget2',
        61  => 'Unknown61',
        62  => 'Unknown62',
        63  => 'Swarm Pet',
        64  => 'Monster Summoning',
        65  => 'Trap',
        66  => 'Timer',
        67  => 'Trigger',
        68  => 'Unknown68',
        69  => 'Unknown69',
        70  => 'Unknown70',
        71  => 'Unknown71',
        72  => 'Unknown72',
        73  => 'Unknown73',
        74  => 'Unknown74',
        75  => 'Unknown75',
        76  => 'Unknown76',
        77  => 'Unknown77',
        78  => 'Unknown78',
        79  => 'Unknown79',
        80  => 'Unknown80',
        81  => 'Unknown81',
        82  => 'Unknown82',
        83  => 'Unknown83',
        84  => 'Unknown84',
        85  => 'Unknown85',
        86  => 'Unknown86',
        87  => 'Unknown87',
        88  => 'Unknown88',
        89  => 'Unknown89',
        90  => 'Unknown90',
        91  => 'Unknown91',
        92  => 'Unknown92',
        93  => 'Unknown93',
        94  => 'Unknown94',
        95  => 'Unknown95',
        96  => 'Unknown96',
        97  => 'Unknown97',
        98  => 'Unknown98',
        99  => 'Unknown99',
        100 => 'Property Utility', //Untargetable
        101 => 'Property Trap',
        102 => 'Property Companion',
        103 => 'Property Suicide'
    ],

    'npc_class' => [
        0  => 'Soldier',
        1  => 'Warrior',
        2  => 'Cleric',
        3  => 'Paladin',
        4  => 'Ranger',
        5  => 'Shadowknight',
        6  => 'Druid',
        7  => 'Monk',
        8  => 'Bard',
        9  => 'Rogue',
        10 => 'Shaman',
        11 => 'Necromancer',
        12 => 'Wizard',
        13 => 'Magician',
        14 => 'Enchanter',
        15 => 'Beastlord',
        16 => 'Berserker',
        17 => 'Banker',
        18 => 'Unknown18',
        19 => 'Unknown19',
        20 => 'Warrior GM',
        21 => 'Cleric GM',
        22 => 'Paladin GM',
        23 => 'Ranger GM',
        24 => 'Shadowknight GM',
        25 => 'Druid GM',
        26 => 'Monk GM',
        27 => 'Bard GM',
        28 => 'Rogue GM',
        29 => 'Shaman GM',
        30 => 'Necromancer GM',
        31 => 'Wizard GM',
        32 => 'Magician GM',
        33 => 'Enchanter GM',
        34 => 'Beastlord GM',
        35 => 'Berserker GM',
        36 => 'Unknown36',
        37 => 'Unknown37',
        38 => 'Unknown38',
        39 => 'Unknown39',
        40 => 'Banker',
        41 => 'Shopkeeper',
        42 => 'Unknown42',
        43 => 'Unknown43',
        44 => 'Unknown44',
        45 => 'Unknown45',
        46 => 'Unknown46',
        47 => 'Unknown47',
        48 => 'Unknown48',
        49 => 'Unknown49',
        50 => 'Unknown50',
        51 => 'Unknown51',
        52 => 'Unknown52',
        53 => 'Unknown53',
        54 => 'Unknown54',
        55 => 'Unknown55',
        56 => 'Unknown56',
        57 => 'Unknown57',
        58 => 'Quest NPC',
        59 => 'Discord Merchant',
        60 => 'LDoN Adventure Recruiter',
        61 => 'LDoN Adventure Merchant',
        62 => 'LDoN Object',
        63 => 'Tribute Master',
        64 => 'Guild Tribute Master',
        65 => 'Unknown65',
        66 => 'Guild Banker',
        67 => 'Norraths Keepers Merchant',
        68 => 'Dark Reign Merchant',
        69 => 'Fellowship Master',
        70 => 'Alt Currency Merchant',
        71 => 'Mercenary Liaison',
        72 => 'Unknown72',
        73 => 'Loyalists of Everquest'
    ],

    // thanks allaclone
    // damage bonuses 2Hands at 65
    //http://lucy.allakhazam.com/dmgbonus.html
    'dmg2h' => [
        0,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14, // 0->9
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14, // 10->19
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        35,
        35, // 20->29
        36,
        36,
        37,
        37,
        38,
        38,
        39,
        39,
        40,
        40, // 30->39
        42,
        42,
        42,
        45,
        45,
        47,
        48,
        49,
        49,
        51, // 40->49
        51,
        52,
        53,
        54,
        54,
        56,
        56,
        57,
        58,
        59, // 50->59
        59,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 60->69
        68,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 70->79
        0,
        0,
        0,
        0,
        0,
        80,
        0,
        0,
        0,
        0, // 80->89
        0,
        0,
        0,
        0,
        0,
        88,
        0,
        0,
        0,
        0, // 90->99
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 100->109
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 110->119
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 120->129
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 130->139
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0, // 140->149
        132,
    ], // 150

    'db_skills' => [
        -1   => 'Hit',
        0   => '1H Blunt',
        1   => '1H Slashing',
        2   => '2H Blunt',
        3   => '2H Slashing',
        4   => 'Abjuration',
        5   => 'Alteration',
        6   => 'Apply Poison',
        7   => 'Archery',
        8   => 'Backstab',
        9   => 'Bind Wound',
        10  => 'Bash',
        11  => 'Block',
        12  => 'Brass',
        13  => 'Channeling',
        14  => 'Conjuration',
        15  => 'Defense',
        16  => 'Disarm',
        17  => 'Disarm Traps',
        18  => 'Divination',
        19  => 'Dodge',
        20  => 'Double Attack',
        21  => 'Dragon Punch',
        22  => 'Dual Wield',
        23  => 'Eagle Strike',
        24  => 'Evocation',
        25  => 'Feign Death',
        26  => 'Flying Kick',
        27  => 'Forage',
        28  => 'Hand To Hand',
        29  => 'Hide',
        30  => 'Kick',
        31  => 'Meditate',
        32  => 'Mend',
        33  => 'Offense',
        34  => 'Parry',
        35  => 'Pick Lock',
        36  => 'Piercing',
        37  => 'Riposte',
        38  => 'Round Kick',
        39  => 'Safe Fall',
        40  => 'Sense Heading',
        41  => 'Singing',
        42  => 'Sneak',
        43  => 'Specialize Abjure',
        44  => 'Specialize Alteration',
        45  => 'Specialize Conjuration',
        46  => 'Specialize Divination',
        47  => 'Specialize Evocation',
        48  => 'Pick Pockets',
        49  => 'Stringed',
        50  => 'Swimming',
        51  => 'Throwing',
        52  => 'Tiger Claw',
        53  => 'Tracking',
        54  => 'Wind',
        55  => 'Fishing',
        56  => 'Make Poison',
        57  => 'Tinkering',
        58  => 'Research',
        59  => 'Alchemy',
        60  => 'Baking',
        61  => 'Tailoring',
        62  => 'Sense Traps',
        63  => 'Blacksmithing',
        64  => 'Fletching',
        65  => 'Brewing',
        66  => 'Alcohol Tolerance',
        67  => 'Begging',
        68  => 'Jewelry Making',
        69  => 'Pottery',
        70  => 'Percussion',
        71  => 'Intimidation',
        72  => 'Berserking',
        73  => 'Taunt',
        74  => 'Frenzy',
        75  => 'Remove Traps',
        76  => 'Triple Attack',
        77  => '2H Piercing',
        98  => 'Melee',
        105 => 'Harm Touch',
        107 => 'Lay Hand',
        111 => 'Slam',
        114 => 'Inspect Chest',
        115 => 'Open Chest',
        116 => 'Reveal Trap Chest',
    ],

    'db_bard_skills' => [
        23 => 'Wind',
        24 => 'Strings',
        25 => 'Brass',
        26 => 'Percussions',
        50 => 'Singing',
        51 => 'All instruments',
    ],

    'db_aug_restrict' => [
        1   => 'Armor Only',
        2   => 'Weapons Only',
        3   => '1h Weapons Only',
        4   => '2h Weapons Only',
        5   => '1h Slash Only',
        6   => '1h Blunt Only',
        7   => 'Piercing Only',
        8   => 'Hand To Hand Only',
        9   => '2h Slash Only',
        10  => '2h Blunt Only',
        11  => '2h Pierce Only',
        12  => 'Bows Only',
    ],

    'db_spell_worn_attribute_cap' => [
        -1  => 'Base_Stats',
        0   => 'STR',
        1   => 'STA',
        2   => 'AGI',
        3   => 'DEX',
        4   => 'WIS',
        5   => 'INT',
        6   => 'CHA',
        7   => 'Magic Resist',
        8   => 'Cold Resist',
        9   => 'Fire Resist',
        10  => 'Poison Resist',
        11  => 'Disease Resist',
        13  => 'Corruption Resis',
    ],

    'db_spell_petcmds' => [
        0   => '/pethealth',
        1   => '/petleader',
        2   => '/petattack',
        3   => '/petqattack',
        4   => '/petfollow',
        5   => '/petguard',
        6   => '/petsit',
        7   => '/petsiton',
        8   => '/petsitoff',
        9   => '/petstop',
        10  => '/petstopon',
        11  => '/petstopoff',
        12  => '/pettaunt',
        13  => '/pettaunton',
        14  => '/pettauntoff',
        15  => '/pethold',
        16  => '/petholdon',
        17  => '/petholdoff',
        18  => '/petghold',
        19  => '/petgholdon',
        20  => '/petgholdoff',
        21  => '/petspellhold',
        22  => '/petspellholdon',
        23  => '/petspellholdoff',
        24  => '/petfocus',
        25  => '/petfocuson',
        26  => '/petfocusoff',
        27  => '/petfeign',
        28  => '/petbackoff',
        29  => '/petgetlost',
        30  => '/petfollow',
        31  => '/petregroup',
        32  => '/petregroupon',
        33  => '/petregroupof',
    ],

    'skills' => [
        'combat' => [
            0   => '1H Blunt',
            1   => '1H Slashing',
            36  => '1H Piercing',
            2   => '2H Blunt',
            3   => '2H Slashing',
            77  => '2H Piercing',
            7   => 'Archery',
            10  => 'Bash',
            11  => 'Block',
            15  => 'Defense',
            16  => 'Disarm',
            19  => 'Dodge',
            20  => 'Double Attack',
            22  => 'Dual Wield',
            28  => 'Hand to Hand',
            30  => 'Kick',
            33  => 'Offense',
            34  => 'Parry',
            37  => 'Riposte',
            51  => 'Throwing',
            71  => 'Intimidation',
            73  => 'Taunt',
            76  => 'Triple Attack',

        ],
        'casting' => [
            4   => 'Abjuration',
            5   => 'Alteration',
            13  => 'Channeling',
            14  => 'Conjuration',
            18  => 'Divination',
            24  => 'Evocation',
            31  => 'Meditate',
            43  => 'Specialize Abjure',
            44  => 'Specialize Alteration',
            45  => 'Specialize Conjuration',
            46  => 'Specialize Divination',
            47  => 'Specialize Evocation',
        ],
        'class' => [
            6   => 'Apply Poison',
            8   => 'Backstab',
            17  => 'Disarm Traps',
            21  => 'Dragon Punch',
            23  => 'Eagle Strike',
            25  => 'Feign Death',
            26  => 'Flying Kick',
            32  => 'Mend',
            35  => 'Pick Lock',
            38  => 'Round Kick',
            48  => 'Pick Pockets',
            52  => 'Tiger Claw',
            72  => 'Berserking',
            62  => 'Sense Traps',
            74  => 'Frenzy',
            75  => 'Remove Trap',
            41  => 'Singing',
            12  => 'Brass Instruments',
            49  => 'Stringed Instruments',
            54  => 'Wind Instruments',
            70  => 'Percussion Instruments',
        ],
        'tradeskill' => [
            55  => 'Fishing',
            56  => 'Make Poison',
            57  => 'Tinkering',
            58  => 'Research',
            59  => 'Alchemy',
            60  => 'Baking',
            61  => 'Tailoring',
            63  => 'Blacksmithing',
            64  => 'Fletching',
            65  => 'Brewing',
            68  => 'Jewelry Making',
            69  => 'Pottery',
        ],
        'misc' => [
            9   => 'Bind Wound',
            27  => 'Forage',
            29  => 'Hide',
            39  => 'Safe Fall',
            40  => 'Sense Heading',
            42  => 'Sneak',
            50  => 'Swimming',
            53  => 'Tracking',
            66  => 'Alcohol Tolerance',
            67  => 'Begging',
        ],
        'languages' => [
            0   => 'Common Tongue',
            1   => 'Barbarian',
            2   => 'Erudian',
            3   => 'Elvish',
            4   => 'Dark Elvish',
            5   => 'Dwarvish',
            6   => 'Troll',
            7   => 'Ogre',
            8   => 'Gnomish',
            9   => 'Halfling',
            10  => 'Thieves Cant',
            11  => 'Old Erudian',
            12  => 'Elder Elvish',
            13  => 'Froglok',
            14  => 'Goblin',
            15  => 'Gnoll',
            16  => 'Combine Tongue',
            17  => 'Elder Teir\'Dal',
            18  => 'Lizardman',
            19  => 'Orcish',
            20  => 'Faerie',
            21  => 'Dragon',
            22  => 'Elder Dragon',
            23  => 'Dark Speech',
            24  => 'Vah Shir',
            25  => 'Alaran',
            26  => 'Hadal',
            27  => 'Unknown',
        ],
    ],

    // https://github.com/EQEmu/eqemu-docs-v2/blob/main/docs/server/player/languages.md
    'languages' => [
        0   => 'Common Tongue',
        1   => 'Barbarian',
        2   => 'Erudian',
        3   => 'Elvish',
        4   => 'Dark Elvish',
        5   => 'Dwarvish',
        6   => 'Troll',
        7   => 'Ogre',
        8   => 'Gnomish',
        9   => 'Halfling',
        10  => 'Thieves Cant',
        11  => 'Old Erudian',
        12  => 'Elder Elvish',
        13  => 'Froglok',
        14  => 'Goblin',
        15  => 'Gnoll',
        16  => 'Combine Tongue',
        17  => 'Elder Teir\'Dal',
        18  => 'Lizardman',
        19  => 'Orcish',
        20  => 'Faerie',
        21  => 'Dragon',
        22  => 'Elder Dragon',
        23  => 'Dark Speech',
        24  => 'Vah Shir',
        25  => 'Alaran',
        26  => 'Hadal',
        27  => 'Unknown',
    ],

    // https://github.com/EQEmu/eqemu-docs-v2/blob/main/docs/server/player/deity-list.md
    'deity' => [
        140 => 'Agnostic',
        396 => 'Agnostic',
        201 => 'Bertoxxulous',
        202 => 'Brell Serilis',
        203 => 'Cazic Thule',
        204 => 'Erollsi Marr',
        205 => 'Bristlebane',
        206 => 'Innoruuk',
        207 => 'Karana',
        208 => 'Mithaniel Marr',
        209 => 'Prexus',
        210 => 'Quellious',
        211 => 'Rallos Zek',
        212 => 'Rodcet Nife',
        213 => 'Solusek Ro',
        214 => 'The Tribunal',
        215 => 'Tunare',
        216 => 'Veeshan',
    ],

    'aa_types' => [
        0  => 'Not Applicable',
        1  => 'General',
        2  => 'Archetype',
        3  => 'Class',
        4  => 'Planes of Power Advanced',
        5  => 'Planes of Power Abilities',
        6  => 'Gates of Discord',
        7  => 'Omens of War',
        8  => 'Veteran',
        9  => 'Dragons of Norrath',
        10 => 'Depths of Darkhollow',
    ],

    'aa_categories' => [
        -1 => 'None',
        1  => 'Passive',
        2  => 'Progression',
        3  => 'Shroud Passive',
        4  => 'Shroud Active',
        5  => 'Veteran Reward',
        6  => 'Tradeskill',
        7  => 'Expendable',
        8  => 'Racial Innate',
        9  => 'EverQuest',
    ],

    // spell targets
    'spell_targets' => [
        0   => 'Rag\'Zhezum Special',
        1   => 'Line of Sight',
        2   => 'AE PC v1',
        3   => 'Group v1',
        4   => 'PB AE',
        5   => 'Single',
        6   => 'Self',
        8   => 'Targeted AE',
        9   => 'Animal',
        10  => 'Undead',
        11  => 'Summoned',
        13  => 'Lifetap',
        14  => 'Pet',
        15  => 'Corpse',
        16  => 'Plant',
        17  => 'Uber Giants',
        18  => 'Uber Dragons',
        20  => 'Targeted AE Tap',
        24  => 'AE Undead',
        25  => 'AE Summoned',
        32  => 'Hatelist',
        33  => 'Hatelist2',
        34  => 'Chest',
        35  => 'Special Muramites',
        36  => 'Caster PB PC',
        37  => 'Caster PB NPC',
        38  => 'Pet2',
        39  => 'No Pets',
        40  => 'AE PC v2',
        41  => 'Group v2',
        42  => 'Directional AE',
        43  => 'Single in Group',
        44  => 'Beam',
        45  => 'Free Target',
        46  => 'Target of Target',
        47  => 'Pet Owner',
        50  => 'Target AE No Players Pets',
    ],

    'spell_target_colors' => [
        0 => 'border border-red-500',
        1 => 'border border-red-500',
        2 => 'border border-indigo-200',
        3 => 'border border-purple-500',
        4 => 'border border-indigo-200',
        5 => 'border border-red-500',
        6 => 'border border-yellow-500',
        8 => 'border border-green-300',
        9 => 'border border-red-500',
        11 => 'border border-red-500',
        13 => 'border border-red-500',
        14 => 'border border-red-500',
        15 => 'border border-red-500',
        16 => 'border border-red-500',
        17 => 'border border-red-500',
        18 => 'border border-red-500',
        20 => 'border border-red-500',
        24 => 'border border-indigo-200',
        25 => 'border border-indigo-200',
        32 => 'border border-neutral-900',
        33 => 'border border-neutral-900',
        34 => 'border border-red-500',
        35 => 'border border-red-500',
        36 => 'border border-neutral-900',
        37 => 'border border-neutral-900',
        38 => 'border border-red-500',
        39 => 'border border-red-500',
        40 => 'border border-purple-500',
        41 => 'border border-purple-500',
        42 => 'border border-teal-500',
        43 => 'border border-red-500',
        44 => 'border border-teal-500',
        45 => 'border border-green-500',
        46 => 'border border-purple-200',
        47 => 'border border-red-500',
    ],

    'spell_effects' => [
        0   => 'Current HP',
        1   => 'AC',
        2   => 'ATK',
        3   => 'Movement Speed',
        4   => 'STR',
        5   => 'DEX',
        6   => 'AGI',
        7   => 'STA',
        8   => 'INT',
        9   => 'WIS',
        10  => 'CHA',
        11  => 'Attack Speed',
        12  => 'Invisibility',
        13  => 'See Invis',
        14  => 'Water Breathing',
        15  => 'Current Mana',
        16  => 'NPC Frenzy',
        17  => 'NPC Awareness',
        18  => 'Lull',
        19  => 'Add Faction',
        20  => 'Blind',
        21  => 'Stun',
        22  => 'Charm',
        23  => 'Fear',
        24  => 'Stamina',
        25  => 'Bind Affinity',
        26  => 'Gate',
        27  => 'Cancel Magic',
        28  => 'Invis vs Undead',
        29  => 'Invis vs Animals',
        30  => 'Change Frenzy Radius',
        31  => 'Mez',
        32  => 'Summon Item',
        33  => 'Summon Pet',
        34  => 'Confuse',
        35  => 'Disease Counter',
        36  => 'Poison Counter',
        37  => 'Detect Hostile',
        38  => 'Detect Magic',
        39  => 'Twincast Blocker',
        40  => 'Divine Aura',
        41  => 'Destroy',
        42  => 'Shadow Step',
        43  => 'Berserk',
        44  => 'Lycanthropy',
        45  => 'Vampirism',
        46  => 'Resist Fire',
        47  => 'Resist Cold',
        48  => 'Resist Poison',
        49  => 'Resist Disease',
        50  => 'Resist Magic',
        51  => 'Detect Traps',
        52  => 'Sense Undead',
        53  => 'Sense Summoned',
        54  => 'Sense Animals',
        55  => 'Rune',
        56  => 'True North',
        57  => 'Levitate',
        58  => 'Illusion',
        59  => 'Damage Shield',
        60  => 'Transfer Item',
        61  => 'Identify',
        62  => 'Item ID',
        63  => 'Wipe Hate List',
        64  => 'Spin Target',
        65  => 'Infra Vision',
        66  => 'Ultra Vision',
        67  => 'Eye of Zomm',
        68  => 'Reclaim Pet',
        69  => 'Total HP',
        70  => 'Corpse Bomb',
        71  => 'Necro Pet',
        72  => 'Preserve Corpse',
        73  => 'Bind Sight',
        74  => 'Feign Death',
        75  => 'Voice Graft',
        76  => 'Sentinel',
        77  => 'Locate Corpse',
        78  => 'Absorb Magic Attack',
        79  => 'Current HP Once',
        80  => 'Enchant Light',
        81  => 'Revive',
        82  => 'Summon PC',
        83  => 'Teleport',
        84  => 'Toss Up',
        85  => 'Weapon Proc',
        86  => 'Harmony',
        87  => 'Magnify Vision',
        88  => 'Succor',
        89  => 'Model Size',
        90  => 'Cloak',
        91  => 'Summon Corpse',
        92  => 'Instant Hate',
        93  => 'Stop Rain',
        94  => 'Negate if Combat',
        95  => 'Sacrifice',
        96  => 'Silence',
        97  => 'Mana Pool',
        98  => 'Attack Speed 2',
        99  => 'Root',
        100 => 'Heal Over Time',
        101 => 'Complete Heal',
        102 => 'Fearless',
        103 => 'Call Pet',
        104 => 'Translocate',
        105 => 'Anti-Gate',
        106 => 'Summon Beast Pet',
        107 => 'Alter NPC Level',
        108 => 'Familiar',
        109 => 'Create Item Into Bag',
        110 => 'Increase Archery',
        111 => 'Resist All',
        112 => 'Casting Level',
        113 => 'Summon Horse',
        114 => 'Change Aggro',
        115 => 'Hunger',
        116 => 'Curse Counter',
        117 => 'Magic Weapon',
        118 => 'Amplification',
        119 => 'Attack Speed 3',
        120 => 'Heal Rate',
        121 => 'Reverse DS',
        122 => 'Reduce Skill',
        123 => 'Screech',
        124 => 'Improved Damage',
        125 => 'Improved Heal',
        126 => 'Spell Resist Reduction',
        127 => 'Increase Spell Haste',
        128 => 'Increase Spell Duration',
        129 => 'Increase Range',
        130 => 'Spell Hate Mod',
        131 => 'Reduce Reagent Cost',
        132 => 'Reduce Mana Cost',
        133 => 'Focus: Stun Time Mod',
        134 => 'Limit: Max Level',
        135 => 'Limit: Resist',
        136 => 'Limit: Target',
        137 => 'Limit: Effect',
        138 => 'Limit: Spell Type',
        139 => 'Limit: Spell',
        140 => 'Limit: Min Duration',
        141 => 'Limit: Instant',
        142 => 'Limit: Min Level',
        143 => 'Limit: Cast Time Min',
        144 => 'Limit: Cast Time Max',
        145 => 'Teleport 2',
        146 => 'Electricity Resist',
        147 => 'Percent Heal',
        148 => 'Stacking Command Block',
        149 => 'Stacking Command Overwrite',
        150 => 'Death Save',
        151 => 'Suspend Pet',
        152 => 'Temporary Pets',
        153 => 'Balance HP',
        154 => 'Dispel Detrimental',
        155 => 'Spell Crit Damage Increase',
        156 => 'Illusion Copy',
        157 => 'Spell Damage Shield',
        158 => 'Reflect',
        159 => 'All Stats',
        160 => 'Make Drunk',
        161 => 'Mitigate Spell Damage',
        162 => 'Mitigate Melee Damage',
        163 => 'Negate Attacks',
        164 => 'Appraise LDoN Chest',
        165 => 'Disarm LDoN Trap',
        166 => 'Unlock LDoN Chest',
        167 => 'Pet Power Increase',
        168 => 'Melee Mitigation',
        169 => 'Critical Hit CHance',
        170 => 'Spell Crit Chance',
        171 => 'Crippling Blow Chance',
        172 => 'Avoid Melee Chance',
        173 => 'Riposte Chance',
        174 => 'Dodge Chance',
        175 => 'Parry Chance',
        176 => 'Dual Wield Chance',
        177 => 'Double Attack Chance',
        178 => 'Melee Lifetap',
        179 => 'All Instrument Mod',
        180 => 'Resist Spell Chance',
        181 => 'Resist Fear Chance',
        182 => 'Hundred Hands',
        183 => 'Melee Skill Check',
        184 => 'Hit Chance',
        185 => 'Damage Modifier',
        186 => 'Min Damage Mod',
        187 => 'Balance Mana',
        188 => 'Increase Block Chance',
        189 => 'CurrentEndurance',
        190 => 'Endurance Pool',
        191 => 'Amnesia',
        192 => 'Hate',
        193 => 'Skill Attack',
        194 => 'Fading Memories',
        195 => 'Stun Resist',
        196 => 'Strike Through',
        197 => 'Skill Damage Taken',
        198 => 'Current Endurance Once',
        199 => 'Taunt',
        200 => 'Proc Chance',
        201 => 'Ranged Proc',
        202 => 'Illusion Other',
        203 => 'Mass Group Buff',
        204 => 'Group Fear Immunity',
        205 => 'Rampage',
        206 => 'AE Taunt',
        207 => 'Flesh to Bone',
        208 => 'Purge Poison',
        209 => 'Dispel Beneficial',
        210 => 'Pet Shield',
        211 => 'AE Melee',
        212 => 'Frenzied Devastation',
        213 => 'Pet Max HP',
        214 => 'Max HP Change',
        215 => 'Pet Avoidance',
        216 => 'Accuracy',
        217 => 'Head Shot',
        218 => 'Pet Critical Hit',
        219 => 'Slay Undead',
        220 => 'Skill Damage Amount',
        221 => 'Packrat',
        222 => 'Block Behind',
        223 => 'Double Riposte',
        224 => 'Give Double Riposte',
        225 => 'Give Double Attack',
        226 => 'Two Hand Bash',
        227 => 'Reduce Skill Timer',
        228 => 'Reduce Fall Damage',
        229 => 'Persistent Casting',
        230 => 'Extended Shielding',
        231 => 'Stun Bash Chance',
        232 => 'Divine Save',
        233 => 'Metabolism',
        234 => 'Reduce Apply Poison Time',
        235 => 'Channel Chance Spells',
        236 => 'Free Pet',
        237 => 'Give Pet Group Target',
        238 => 'Illusion Persistence',
        239 => 'Feigned Cast on Chance',
        240 => 'String Unbreakable',
        241 => 'Improve Reclaim Energy',
        242 => 'Increase Chance Memwipe',
        243 => 'Charm Break Chance',
        244 => 'Root Break Chance',
        245 => 'Trap Circumvention',
        246 => 'Set Breath Level',
        247 => 'Raise Skill Cap',
        248 => 'Secondary Forte',
        249 => 'Secondary Damage Increase',
        250 => 'Spell Proc Chance',
        251 => 'Consume Projectile',
        252 => 'Frontal Backstab Chance',
        253 => 'Frontal Backstab Min Damage',
        254 => 'Blank',
        255 => 'Shield Duration',
        256 => 'Shroud of Stealth',
        257 => 'Pet Discipline',
        258 => 'Triple Backstab',
        259 => 'Combat Stability',
        260 => 'Add Singing Mod',
        261 => 'Song Mod Cap',
        262 => 'Raise Stat Cap',
        263 => 'Tradeskill Mastery',
        264 => 'Hastened AA Skill',
        265 => 'Mastery of Past',
        266 => 'Extra Attack Chance',
        267 => 'Add Pet Command',
        268 => 'Reduce Tradeskill Fail',
        269 => 'Max Bind Wound',
        270 => 'Bard Song Range',
        271 => 'Base Movement Speed',
        272 => 'Casting Level 2',
        273 => 'Critical DoT Chance',
        274 => 'Critical Heal Chance',
        275 => 'Critical Mend',
        276 => 'Ambidexterity',
        277 => 'Unfailing Divinity',
        278 => 'Finishing Blow',
        279 => 'Flurry',
        280 => 'Pet Flurry',
        281 => 'Feigned Minion',
        282 => 'Improved Bind Wound',
        283 => 'Double Special Attack',
        284 => 'LoH Set Heal',
        285 => 'Nimble Evasion',
        286 => 'Focus: Damage Amount',
        287 => 'Spell Duration Increase by Tick',
        288 => 'Skill Attack Proc',
        289 => 'Cast on Fade Effect',
        290 => 'Increase Run Speed Cap',
        291 => 'Purify',
        292 => 'Strike Through 2',
        293 => 'Frontal Stun Resist',
        294 => 'Critical Spell Chance',
        295 => 'Reduce Timer Special',
        296 => 'Focus: Spell Vulnerability',
        297 => 'Focus: Damage Amount Incoming',
        298 => 'Change Height',
        299 => 'Wake the Dead',
        300 => 'Doppelganger',
        301 => 'Archery Damage Modifier',
        302 => 'Focus: Damage Percent Crit',
        303 => 'Focus: Damage Amount Crit',
        304 => 'Offhand Riposte Fail',
        305 => 'Mitigate Damage Shield',
        306 => 'Army of the Dead',
        307 => 'Appraisal',
        308 => 'Suspend Minion',
        309 => 'Gate Casters Bindpoint',
        310 => 'Reduce Reuse Timer',
        311 => 'Limit: Combat Skills',
        312 => 'Sanctuary',
        313 => 'Forage Additional Items',
        314 => 'Invisibility 2',
        315 => 'Invis vs Undead 2',
        316 => 'Improved Invis Animals',
        317 => 'Item HP Regen Cap Increase',
        318 => 'Item Mana Regen Cap Increase',
        319 => 'Critical Heal Over Time',
        320 => 'Shield Block',
        321 => 'Reduce Hate',
        322 => 'Gate to Home City',
        323 => 'Defensive Proc',
        324 => 'HP to Mana',
        325 => 'No Break AE Sneak',
        326 => 'Spell Slot Increase',
        327 => 'Mystical Attune',
        328 => 'Delay Death',
        329 => 'Mana Absorb Percent Damage',
        330 => 'Critical Damage Mod',
        331 => 'Salvage',
        332 => 'Summon to Corpse',
        333 => 'Cast on Rune Fade Effect',
        334 => 'Bard AE DoT',
        335 => 'Block Next Spell Focus',
        336 => 'Illusionary Target',
        337 => 'Percent XP Increase',
        338 => 'Summon and Resurrect All Corpses',
        339 => 'Trigger on Cast',
        340 => 'Spell Trigger',
        341 => 'Item Attack Cap Increase',
        342 => 'Immune Fleeing',
        343 => 'Interrupt Casting',
        344 => 'Channel Chance Items',
        345 => 'Assassinate Level',
        346 => 'Head Shot Level',
        347 => 'Double Ranged Attack',
        348 => 'Limit: Mana Min',
        349 => 'Shield Equip Damage Mod',
        350 => 'Mana Burn',
        351 => 'Persistent Effect',
        352 => 'Increase Trap Count',
        353 => 'Additional Aura',
        354 => 'Deactivate All Traps',
        355 => 'Learn Trap',
        356 => 'Change Trigger Type',
        357 => 'Focus: Mute',
        358 => 'Current Mana Once',
        359 => 'Passive Sense Trap',
        360 => 'Proc on Kill Shot',
        361 => 'Spell on Death',
        362 => 'Potion Belt Slots',
        363 => 'Bandolier Slots',
        364 => 'Triple Attack Chance',
        365 => 'Proc on Spell Kill Shot',
        366 => 'Group Shielding',
        367 => 'Set Body Type',
        368 => 'Faction Mod',
        369 => 'Corruption Counter',
        370 => 'Resist Corruption',
        371 => 'Attack Speed 4',
        372 => 'Forage Skill',
        373 => 'Cast on Fade Effect Always',
        374 => 'Apply Effect',
        375 => 'DoT Crit Damage Increase',
        376 => 'Fling',
        377 => 'Cast on Fade Effect NPC',
        378 => 'Spell Effect Resist Chance',
        379 => 'Shadow Step Directional',
        380 => 'Knockdown',
        381 => 'Knock Toward Caster',
        382 => 'Negate Spell Effect',
        383 => 'Sympathetic Proc',
        384 => 'Leap',
        385 => 'Limit: Spell Group',
        386 => 'Cast on Curer',
        387 => 'Cast on Cure',
        388 => 'Summon Corpse Zone',
        389 => 'Focus: Timer Refresh',
        390 => 'Focus: Timer Lockout',
        391 => 'Limit: Mana Max',
        392 => 'Focus: Heal Amt',
        393 => 'Focus: Heal Percent Incoming',
        394 => 'Focus: Heal Amt Incoming',
        395 => 'Focus: Heal Percent Crit Incoming',
        396 => 'Focus: Heal Amt Crit',
        397 => 'Pet Melee Mitigation',
        398 => 'Swarm Pet Duration',
        399 => 'Focus: Twincast',
        400 => 'Heal Group from Mana',
        401 => 'Mana Drain with Dmg',
        402 => 'Endurance Drain with Dmg',
        403 => 'Limit: Spell Class',
        404 => 'Limit: Spell Subclass',
        405 => 'Two Hand Blunt Block',
        406 => 'Cast on Num Hit Fade',
        407 => 'Cast on Focus Effect',
        408 => 'Limit: HP Percent',
        409 => 'Limit: Mana Percent',
        410 => 'Limit: Endurance Percent',
        411 => 'Limit: Class',
        412 => 'Limit: Race',
        413 => 'Focus: Base Effects',
        414 => 'Limit: Casting Skill',
        415 => 'Limit: Item Class',
        416 => 'AC v2',
        417 => 'Mana Regen v2',
        418 => 'Skill Damage Amount 2',
        419 => 'Add Melee Proc',
        420 => 'Focus: Limit Use',
        421 => 'Focus: Increase Num Hits',
        422 => 'Limit: Use Min',
        423 => 'Limit: Use Type',
        424 => 'Gravity Effect',
        425 => 'Display',
        426 => 'Increase Ext Target Window',
        427 => 'Skill Proc',
        428 => 'Limit to Skill',
        429 => 'Skill Proc Success',
        430 => 'Post Effect',
        431 => 'Post Effect Data',
        432 => 'Expand Max Active Trophy Benefits',
        433 => 'Critical DoT Decay',
        434 => 'Critical Heal Decay',
        435 => 'Critical Regen Decay',
        436 => 'Beneficial Countdown Hold',
        437 => 'Teleport to Anchor',
        438 => 'Translocate to Anchor',
        439 => 'Assassinate',
        440 => 'Finishing Blow Level',
        441 => 'Distance Removal',
        442 => 'Trigger on Req Target',
        443 => 'Trigger on Req Caster',
        444 => 'Improved Taunt',
        445 => 'Add Merc Slot',
        446 => 'A Stacker',
        447 => 'B Stacker',
        448 => 'C Stacker',
        449 => 'D Stacker',
        450 => 'Mitigate DoT Damage',
        451 => 'Melee Threshold Guard',
        452 => 'Spell Threshold Guard',
        453 => 'Trigger Melee Threshold',
        454 => 'Trigger Spell Threshold',
        455 => 'Add Hate Percent',
        456 => 'Add Hate Over Time Percent',
        457 => 'Resource Tap',
        458 => 'Faction Mod Percent',
        459 => 'Damage Modifier 2',
        460 => 'Limit: Override Not Focusable',
        461 => 'Improved Damage 2',
        462 => 'Focus: Damage Amount 2',
        463 => 'Shield Target',
        464 => 'PC Pet Rampage',
        465 => 'PC Pet AE Rampage',
        466 => 'Player Pet Flurry Chance',
        467 => 'DS Mitigation Amount',
        468 => 'DS Mitigation Percent',
        469 => 'Chance Best in Spell Group',
        470 => 'Trigger Best in Spell Group',
        471 => 'Double Melee Round',
        472 => 'Buy AA Rank',
        473 => 'Double Backstab Front',
        474 => 'Pet Crit Melee Damage Percent Owner',
        475 => 'Trigger Spell Non-Item',
        476 => 'Weapon Stance',
        477 => 'Hatelist to Top Index',
        478 => 'Hatelist to Tail Index',
        479 => 'Limit: Value Min',
        480 => 'Limit: Value Max',
        481 => 'Focus: Cast Spell on Land',
        482 => 'Skill Base Damage Mod',
        483 => 'Focus: Spell Damage Percent Incoming PC',
        484 => 'Focus: Spell Damage Amount Incoming PC',
        485 => 'Limit: Caster Class',
        486 => 'Limit: Same Caster',
        487 => 'Extend Tradeskill Cap',
        488 => 'Defender Melee Force Percent PC',
        489 => 'Worn Endurance Regen Cap',
        490 => 'Limit: Reuse Time Min',
        491 => 'Limit: Reuse Time Max',
        492 => 'Limit: Endurance Min',
        493 => 'Limit: Endurance Max',
        494 => 'Pet Add Attack',
        495 => 'Limit: Duration Max',
        496 => 'Critical Melee Damage Mod Max',
        497 => 'Limit: Focus Cast Proc No Bypass',
        498 => 'Add Extra Attack Percent 1H PRI',
        499 => 'Add Extra Attack Percent 1H SEC',
        500 => 'Focus: Cast Time Mod 2',
        501 => 'Focus: Cast Time Amount',
        502 => 'Fearstun',
        503 => 'Melee Damage Position Mod',
        504 => 'Melee Damage Position Amount',
        505 => 'Damage Taken Position Mod',
        506 => 'Damage Taken Position Amount',
        507 => 'Focus: Amplify Mod',
        508 => 'Focus: Amplify Amount',
        509 => 'Health Transfer',
        510 => 'Focus: Resist Incoming',
        511 => 'Limit: Focus Timer Min',
        512 => 'Proc Timer Modifier',
        513 => 'Mana Max Percent',
        514 => 'Endurance Max Percent',
        515 => 'AC Avoidance Max Percent',
        516 => 'AC Mitigation Max Percent',
        517 => 'Attack Offense Max Percent',
        518 => 'Attack Accuracy Max Percent',
        519 => 'Luck Amount',
        520 => 'Luck Percent',
        521 => 'Endurance Absorb Percent Damage',
        522 => 'Instant Mana Percent',
        523 => 'Instant Endurance Percent',
        524 => 'Duration HP Percent',
        525 => 'Duration Mana Percent',
        526 => 'Duration Endurance Percent',
    ],

    // spell target restrictions
    'spell_target_restrictions' => [
        0       => 'None',
        3       => 'Unknown 3',
        5       => 'Is Not On Horse',
        100     => 'Is Animal Or Humanoid',
        101     => 'Is Dragon',
        102     => 'Is Animal Or Insect',
        103     => 'Is Body Type Misc',
        104     => 'Is Body Type Misc2',
        105     => 'Is Plant',
        106     => 'Is Giant',
        108     => 'Is Not Animal Or Humanoid',
        109     => 'Is Bixie',
        110     => 'Is Harpy',
        111     => 'Is Gnoll',
        112     => 'Is Sporali',
        113     => 'Is Kobold',
        114     => 'Is Frostcrypt Shade',
        115     => 'Is Drakkin',
        116     => 'Is Undead Or Valdeholm Giant',
        117     => 'Is Animal Or Plant',
        118     => 'Is Summoned',
        119     => 'Is Wizard Used On Mage Fire Pet',
        120     => 'Is Undead',
        121     => 'Is Not Undead Or Summoned Or Vampire',
        122     => 'Is Fae Or Pixie',
        123     => 'Is Humanoid',
        124     => 'Is Undead And Hp Less Than 10 Pct',
        125     => 'Is Clockwork And Hp Less Than 45 Pct',
        126     => 'Is Wisp And Hp Less Than 10 Pct',
        127     => 'Is Class Melee That Can Bash Or Kick Except Bard',
        128     => 'Is Class Pure Melee',
        129     => 'Is Class Pure Caster',
        130     => 'Is Class Hybrid Class',
        131     => 'Is Class Warrior',
        132     => 'Is Class Cleric',
        133     => 'Is Class Paladin',
        134     => 'Is Class Ranger',
        135     => 'Is Class Shadowknight',
        136     => 'Is Class Druid',
        137     => 'Is Class Monk',
        138     => 'Is Class Bard',
        139     => 'Is Class Rogue',
        140     => 'Is Class Shaman',
        141     => 'Is Class Necro',
        142     => 'Is Class Wizard',
        143     => 'Is Class Mage',
        144     => 'Is Class Enchanter',
        145     => 'Is Class Beastlord',
        146     => 'Is Class Berserker',
        147     => 'Is Class Clr Shm Dru',
        148     => 'Is Class Not War Pal Sk',
        150     => 'Is Level Under 100',
        190     => 'Is Not Raid Boss',
        191     => 'Is Raid Boss',
        192     => 'Frenzied Burnout Active',
        193     => 'Frenzied Burnout Not Active',
        199     => 'Unknown 199',
        201     => 'Is Hp Above 75 Pct',
        203     => 'Is Hp Less Than 20 Pct',
        204     => 'Is Hp Less Than 50 Pct',
        205     => 'Is Hp Less Than 75 Pct',
        216     => 'Is Not In Combat',
        221     => 'Has At Least 1 Pet On Hatelist',
        222     => 'Has At Least 2 Pets On Hatelist',
        223     => 'Has At Least 3 Pets On Hatelist',
        224     => 'Has At Least 4 Pets On Hatelist',
        225     => 'Has At Least 5 Pets On Hatelist',
        226     => 'Has At Least 6 Pets On Hatelist',
        227     => 'Has At Least 7 Pets On Hatelist',
        228     => 'Has At Least 8 Pets On Hatelist',
        229     => 'Has At Least 9 Pets On Hatelist',
        230     => 'Has At Least 10 Pets On Hatelist',
        231     => 'Has At Least 11 Pets On Hatelist',
        232     => 'Has At Least 12 Pets On Hatelist',
        233     => 'Has At Least 13 Pets On Hatelist',
        234     => 'Has At Least 14 Pets On Hatelist',
        235     => 'Has At Least 15 Pets On Hatelist',
        236     => 'Has At Least 16 Pets On Hatelist',
        237     => 'Has At Least 17 Pets On Hatelist',
        238     => 'Has At Least 18 Pets On Hatelist',
        239     => 'Has At Least 19 Pets On Hatelist',
        240     => 'Has At Least 20 Pets On Hatelist',
        250     => 'Is Hp Less Than 35 Pct',
        260     => 'Has Between 1 To 2 Pets On Hatelist',
        261     => 'Has Between 3 To 5 Pets On Hatelist',
        262     => 'Has Between 6 To 9 Pets On Hatelist',
        263     => 'Has Between 10 To 14 Pets On Hatelist',
        264     => 'Has More Than 14 Pets On Hatelist',
        304     => 'Is Class Chain Or Plate',
        350     => 'Is Hp Between 5 And 9 Pct',
        351     => 'Is Hp Between 10 And 14 Pct',
        352     => 'Is Hp Between 15 And 19 Pct',
        353     => 'Is Hp Between 20 And 24 Pct',
        354     => 'Is Hp Between 25 And 29 Pct',
        355     => 'Is Hp Between 30 And 34 Pct',
        356     => 'Is Hp Between 35 And 39 Pct',
        357     => 'Is Hp Between 40 And 44 Pct',
        358     => 'Is Hp Between 45 And 49 Pct',
        359     => 'Is Hp Between 50 And 54 Pct',
        360     => 'Is Hp Between 55 And 59 Pct',
        398     => 'Is Hp Between 5 And 15 Pct',
        399     => 'Is Hp Between 15 And 25 Pct',
        400     => 'Is Hp Between 1 And 25 Pct',
        401     => 'Is Hp Between 25 And 35 Pct',
        402     => 'Is Hp Between 35 And 45 Pct',
        403     => 'Is Hp Between 45 And 55 Pct',
        404     => 'Is Hp Between 55 And 65 Pct',
        405     => 'Is Hp Between 65 And 75 Pct',
        406     => 'Is Hp Between 75 And 85 Pct',
        407     => 'Is Hp Between 85 And 95 Pct',
        408     => 'Is Hp Above 45 Pct',
        409     => 'Is Hp Above 55 Pct',
        410     => 'Unknown Too Much Hp 410',
        411     => 'Unknown Too Much Hp 411',
        412     => 'Is Hp Above 99 Pct',
        429     => 'Is Mana Above 10 Pct',
        501     => 'Is Hp Below 5 Pct',
        502     => 'Is Hp Below 10 Pct',
        503     => 'Is Hp Below 15 Pct',
        504     => 'Is Hp Below 20 Pct',
        505     => 'Is Hp Below 25 Pct',
        506     => 'Is Hp Below 30 Pct',
        507     => 'Is Hp Below 35 Pct',
        508     => 'Is Hp Below 40 Pct',
        509     => 'Is Hp Below 45 Pct',
        510     => 'Is Hp Below 50 Pct',
        511     => 'Is Hp Below 55 Pct',
        512     => 'Is Hp Below 60 Pct',
        513     => 'Is Hp Below 65 Pct',
        514     => 'Is Hp Below 70 Pct',
        515     => 'Is Hp Below 75 Pct',
        516     => 'Is Hp Below 80 Pct',
        517     => 'Is Hp Below 85 Pct',
        518     => 'Is Hp Below 90 Pct',
        519     => 'Is Hp Below 95 Pct',
        521     => 'Is Mana Below Unknown Pct',
        522     => 'Is Endurance Below 40 Pct',
        523     => 'Is Mana Below 40 Pct',
        524     => 'Is Hp Above 20 Pct',
        600     => 'Is Body Type Undefined',
        601     => 'Is Body Type Humanoid',
        602     => 'Is Body Type Werewolf',
        603     => 'Is Body Type Undead',
        604     => 'Is Body Type Giants',
        605     => 'Is Body Type Constructs',
        606     => 'Is Body Type Extraplanar',
        607     => 'Is Body Type Magical Creature',
        608     => 'Is Body Type Undeadpet',
        609     => 'Is Body Type Kaelgiant',
        610     => 'Is Body Type Coldain',
        612     => 'Is Body Type Vampire',
        613     => 'Is Body Type Aten Ha Ra',
        614     => 'Is Body Type Greater Ahkevans',
        615     => 'Is Body Type Khati Sha',
        616     => 'Is Body Type Lord Inquisitor Seru',
        617     => 'Is Body Type Grieg Veneficus',
        619     => 'Is Body Type From Plane Of War',
        620     => 'Is Body Type Luggald',
        621     => 'Is Body Type Animal',
        622     => 'Is Body Type Insect',
        623     => 'Is Body Type Monster',
        624     => 'Is Body Type Elemental',
        625     => 'Is Body Type Plant',
        626     => 'Is Body Type Dragon2',
        627     => 'Is Body Type Summoned Elemental',
        628     => 'Is Body Type Warder',
        630     => 'Is Body Type Dragon Of Tov',
        631     => 'Is Body Type Familiar',
        634     => 'Is Body Type Muramite',
        635     => 'Is Not Undead Or Summoned',
        636     => 'Is Not Plant',
        700     => 'Is Not Client',
        701     => 'Is Client',
        800     => 'Is Level Above 42 And Is Client',
        812     => 'Unknown 812',
        814     => 'Unknown 814',
        815     => 'Is Treant',
        816     => 'Is Bixie2',
        817     => 'Is Scarecrow',
        818     => 'Is Vampire Or Undead Or Undeadpet',
        819     => 'Is Not Vampire Or Undead',
        820     => 'Is Class Knight Hybrid Melee',
        821     => 'Is Class Warrior Caster Priest',
        822     => 'Unknown 822',
        825     => 'Is End Below 21 Pct',
        826     => 'Is End Below 25 Pct',
        827     => 'Is End Below 29 Pct',
        836     => 'Is Regular Server',
        837     => 'Is Progression Server',
        839     => 'Is God Expansion Unlocked',
        840     => 'Unknown 840',
        841     => 'Unknown 841',
        842     => 'Is Humanoid Level 84 Max',
        843     => 'Is Humanoid Level 86 Max',
        844     => 'Is Humanoid Level 88 Max',
        845     => 'Has Crystallized Flame Buff',
        847     => 'Has Incendiary Ooze Buff',
        860     => 'Is Level 90 Max',
        861     => 'Is Level 92 Max',
        862     => 'Is Level 94 Max',
        863     => 'Is Level 95 Max',
        864     => 'Is Level 97 Max',
        865     => 'Is Level 99 Max',
        866     => 'Has Weaponstance Defensive Proficiency',
        867     => 'Has Weaponstance Two Hand Proficiency',
        868     => 'Has Weaponstance Dual Weild Proficiency',
        869     => 'Is Level 100 Max',
        870     => 'Is Level 102 Max',
        871     => 'Is Level 104 Max',
        872     => 'Is Level 105 Max',
        873     => 'Is Level 107 Max',
        874     => 'Is Level 109 Max',
        875     => 'Is Level 110 Max',
        876     => 'Is Level 112 Max',
        877     => 'Is Level 114 Max',
        997     => 'Has Tbl Esianti Access',
        999     => 'Has Item Clockwork Scraps',
        1000    => 'Is Between Level 1 And 75',
        1001    => 'Is Between Level 76 And 85',
        1002    => 'Is Between Level 86 And 95',
        1003    => 'Is Between Level 96 And 105',
        1004    => 'Is Hp Less Than 80 Pct',
        1474    => 'Is Level Above 34',
        2000    => 'In Two Handed Stance',
        2001    => 'In Dual Wield Handed Stance',
        2002    => 'In Shield Stance',
        2010    => 'Not In Two Handed Stance',
        2011    => 'Not In Dual Wield Handed Stance',
        2012    => 'Not In Shield Stance',
        2761    => 'Level 46 Max',
        7000    => 'Disabled Until Expansion Rok',
        7001    => 'Disabled Until Expansion Sov',
        7002    => 'Disabled Until Expansion Sol',
        7003    => 'Disabled Until Expansion Pop',
        7004    => 'Disabled Until Expansion Loy',
        7005    => 'Disabled Until Expansion Ldon',
        7006    => 'Disabled Until Expansion God',
        7007    => 'Disabled Until Expansion Oow',
        7008    => 'Disabled Until Expansion Don',
        7009    => 'Disabled Until Expansion Dod',
        7010    => 'Disabled Until Expansion Por',
        7011    => 'Disabled Until Expansion Tss',
        7012    => 'Disabled Until Expansion Tbs',
        7013    => 'Disabled Until Expansion Sof',
        7014    => 'Disabled Until Expansion Sod',
        7015    => 'Disabled Until Expansion Uf',
        7016    => 'Disabled Until Expansion Hot',
        7017    => 'Disabled Until Expansion Voa',
        7018    => 'Disabled Until Expansion Rof',
        7019    => 'Disabled Until Expansion Cof',
        7020    => 'Disabled Until Expansion Tds',
        7021    => 'Disabled Until Expansion Tbm',
        7022    => 'Disabled Until Expansion Eok',
        7023    => 'Disabled Until Expansion Ros',
        7024    => 'Disabled Until Expansion Tbl',
        7025    => 'Disabled Until Expansion Tov',
        7026    => 'Disabled Until Expansion Cov',
        8450    => 'Has No Mana Burn Buff',
        10000   => 'Is Race First Custom',
        11000   => 'Is Race Last Custom',
        11044   => 'Is Client And Male Plate User',
        11090   => 'Is Cleint And Male Dru Encr Mag Nec Shm Or Wiz',
        11209   => 'Is Client And Male Bst Ber Mnk Rng Or Rog',
        11210   => 'Is Client And Female Plate User',
        11211   => 'Is Client And Female Dru Encr Mag Nec Shm Or Wiz',
        11248   => 'Is Client And Female Bst Ber Mnk Rng Or Rog',
        11260   => 'Has Traveled To Stratos',
        11261   => 'Has Traveled To Aalishai',
        11268   => 'Has Traveled To Mearats',
        12519   => 'Has No Illusions Of Grandeur Buff',
        16010   => 'Is Hp Above 50 Pct',
        16031   => 'Is Hp Under 50 Pct',
        27672   => 'Is Off Hand Equiped',
        29556   => 'Has No Pact Of Fate Recourse Buff',
        32339   => 'Has No Shroud Of Prayer Buff',
        38311   => 'Is Mana Below 20 Pct',
        38312   => 'Is Mana Above 50 Pct',
        39281   => 'Completed Achievement Legendary Answerer',
        40297   => 'Has No Rogues Fury Buff',
        42280   => 'Not Completed Achievement Legendary Answerer',
        49326   => 'Is Summoned Or Undead',
        49529   => 'Is Class Caster Priest',
        49543   => 'Is End Or Mana Above 20 Pct',
        49573   => 'Is End Or Mana Below 30 Pct',
        49574   => 'Is Class Bard2',
        49575   => 'Is Not Class Bard',
        49612   => 'Has No Furious Rampage Buff',
        49809   => 'Is End Or Mana Below 30 Pct2',
        50003   => 'Has No Harmonious Precision Buff',
        50009   => 'Has No Harmonious Expanse Buff',
        99999   => 'Unknown 9999',
    ],

    // itemtype 14
    'food_types' => [
        'This is a snack!', // 1-5
        'This is a meal!', // 6-20
        'This is a hearty meal!', // 21-30
        'This is a banquet sized meal!', // 31-40
        'This is a feast!', // 41-50
        'This is a enduring meal!', // 51-60
        'This is a miraculous meal!', // 70+
    ],

    // itemtype 15
    'drink_types' => [
        'This is a whistle wetter!', // 1-5
        'This is a drink!', // 6-20
        'This is a refreshing drink!', // 21-30,
        'This is a lasting drink!', // 31-40
        'This is a flowing drink!', // 41
        'This is a enduring drink!', // 51-60
        'This is a miraculous drink!', // 70+
    ],

    // object containers
    'object_containers' => [
        10 => 'Tool Box',
        11 => 'Research',
        12 => 'Mortar', // "Mortar" (Opens experiment combine window)
        13 => 'Self Dusting', // "Self Dusting" (Opens experiment combine window)
        14 => 'Baking',
        15 => 'Baking',
        16 => 'Tailoring',
        17 => 'Forge',
        18 => 'Fletching',
        19 => 'Brew Barrel',
        20 => 'Jewelcraft',
        21 => 'Pottery Wheel',
        22 => 'Pottery Kiln',
        24 => 'Wiz only combine container (Research container?)',
        25 => 'Mage only',
        26 => 'Necro only',
        27 => 'Ench Only',
        28 => 'Unknown', // Invalid or Class/Race limited (Client crash w/DEF NEC)
        29 => 'Unknown', // Invalid or Class/Race limited (Client crash w/DEF NEC)
        30 => 'Unknown', // "Always Works" (Opens experiment combine window)
        31 => 'High Elves Forge',
        32 => 'Dark Elves Forge',
        33 => 'Ogre Forge',
        34 => 'Dwarve Forge',
        35 => 'Gnome Forge',
        36 => 'Barbarian Forge',
        38 => 'Iksar Forge',
        39 => 'Human Forge',
        40 => 'Human Forge',
        41 => 'Halfling Tailoring kit',
        42 => 'Erudite Tailor',
        43 => 'Wood Elf Tailor',
        44 => 'Wood Elf Fletching kit',
        45 => 'Iksar Pottery Wheel',
        47 => 'Troll Forge',
        48 => 'Wood Elf Forge',
        49 => 'Halfling Forge',
        50 => 'Erudite Forge',
        53 => 'Augment',
    ],

    'special_attacks' => [
        1   => 'Summon',
        2   => 'Enrage',
        3   => 'Rampage',
        4   => 'AE Rampage',
        5   => 'Flurry',
        6   => 'Triple Attack',
        7   => 'Quad Attack',
        8   => 'Dual Wield',
        9   => 'Bane Attack',
        10  => 'Magic Attack',
        11  => 'Ranged Attack',
        12  => 'Unslowable',
        13  => 'Unmezable',
        14  => 'Uncharmable',
        15  => 'Unstunable',
        16  => 'Unsnareable',
        17  => 'Unfearable',
        18  => 'Immune to Dispell',
        19  => 'Immune to Melee',
        20  => 'Immune to Magic',
        21  => 'Immune to Fleeing',
        22  => 'Immune to non-Bane Melee',
        23  => 'Immune to non-Magical Melee',
        24  => 'Will Not Aggro',
        25  => 'Immune to Aggro',
        26  => 'Resist Ranged Spells',
        27  => 'See through Feign Death',
        28  => 'Immune to Taunt',
        29  => 'Tunnel Vision',
        30  => 'Does NOT buff/heal friends',
        31  => 'Unpacifiable',
        32  => 'Leashed',
        33  => 'Tethered',
        34  => 'Destructible Object',
        35  => 'No Harm from Players',
        36  => 'Always Flee',
        37  => 'Flee Percent',
        38  => 'Allow Beneficial',
        39  => 'Disable Melee',
        40  => 'Chase Distance',
        41  => 'Allow Tank',
        42  => 'Ignore Root Aggro',
        43  => 'Casting Resist Diff',
        44  => 'Counter Avoid Damage',
        45  => 'Proximity Aggro',
        46  => 'Immune Ranged Attacks',
    ],

    'spell_negatetype' => [
        0 => 'Spell, Item and AA',
        1 => 'Spell',
        2 => 'Item',
        3 => 'Spell and Item',
        4 => 'AA',
        5 => 'Spell and AA',
        6 => 'Item and AA',
    ],

    'spell_numhitstype' => [
        0   => 'None',
        1   => 'Incoming Hit Attempts',
        2   => 'Outgoing Hit Attempts',
        3   => 'Incoming Spells',
        4   => 'Outgoing Spells',
        5   => 'Outgoing Hit Successes',
        6   => 'Incoming Hit Successes',
        7   => 'Matching Spells',
        8   => 'Incoming Hits Or Spells',
        9   => 'Reflected Spells',
        10  => 'Defensive Proc Casts',
        11  => 'Offensive Proc Casts',
        13  => 'Incoming Hits Or Spells Or DS',
        14  => 'Outgoing Hits Affected By Buff',
        15  => 'Tradeskill Combines',
    ],

    'zone_types' => [
        0 => 'Unknown',
        1 => 'Regular',
        2 => 'Instanced',
        3 => 'Hybrid',
        4 => 'Raid',
        5 => 'City',
    ],

    'item_size' => [
        0 => 'Tiny',
        1 => 'Small',
        2 => 'Medium',
        3 => 'Large',
        4 => 'Giant',
    ],

    'task_types' => [
        0 => 'Task',
        1 => 'Shared Task',
        2 => 'Quest',
        3 => 'Expedition',
    ],

    // https://docs.eqemu.io/server/task-system-guide/#activity-types
    'task_activity_types' => [
        1   => 'Deliver',
        2   => 'Kill',
        3   => 'Loot',
        4   => 'Speak With',
        5   => 'Explore',
        6   => 'Tradeskill',
        7   => 'Fish',
        8   => 'Forage',
        9   => 'Use',
        10  => 'Use',
        11  => 'Touch',
        14  => 'Speak With', // ?
        100 => 'Give Cash',
        255 => 'Unknown',
    ],

    'aug_slots' => [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
    ],

    'aug_type_descriptions' => [
        1   => 'General: Single Stat',
        2   => 'General: Multiple Stat',
        3   => 'General: Spell Effect',
        4   => 'General: Group',
        5   => 'Weapon: Elem Damage',
        6   => 'Weapon: Base Damage',
        7   => 'General: Group',
        8   => 'General: Raid',
        9   => 'General: Dragon Points',
        10  => 'Crafted: Common',
        11  => 'Crafted: Group',
        12  => 'Crafted: Raid',
        13  => 'Energeiac: Group',
        14  => 'Energeiac: Raid',
        15  => 'Emblem',
        16  => 'Crafted: Group',
        17  => 'Crafted: Raid',
        18  => '',
        19  => '',
        20  => 'Ornamentation',
        21  => 'Special Ornamentation',
        22  => '',
        23  => '',
        24  => '',
        25  => '',
        26  => '',
        27  => '',
        28  => '',
        29  => '',
        30  => '',
    ],

    'ldon_themes' => [
        1   => 'Guk',
        2   => 'Mir',
        4   => 'Mmc',
        8   => 'Ruj',
        16  => 'Tak',
        31  => 'All',
    ],
];
